// Аудирование: короткий рассказ звучит голосом, текст скрыт.
// text: предложения (en, ru); qs: вопросы по рассказу; pick: «что ты услышал?» (say — что произносится, opts — варианты, верный первым в данных).
// req — id локации, после которой открывается; world — мир (0, 1, 2).
const AUDIOS = [
  { id: 'a1', world: 0, req: 8, icon: '👦', title: 'Знакомься, это Макс', intro: 'Новый друг хочет познакомиться. Послушай, что он расскажет!',
    text: [{ en: 'Hello! My name is Max.', ru: 'Привет! Меня зовут Макс.' }, { en: 'I am seven.', ru: 'Мне семь.' }, { en: 'This is my mum.', ru: 'Это моя мама.' },
      { en: 'This is my dad.', ru: 'Это мой папа.' }, { en: 'I have a brother.', ru: 'У меня есть брат.' }],
    qs: [{ en: 'What is his name?', ru: 'Как его зовут?', ans: 'Max', opts: ['Max', 'Bolt', 'Tom'] },
      { en: 'How old is Max?', ru: 'Сколько лет Максу?', ans: 'Seven', opts: ['Seven', 'Nine', 'Six'] },
      { en: 'Who has Max got?', ru: 'Кто есть у Макса?', ans: 'A brother', opts: ['A brother', 'A sister', 'A dog'] }],
    pick: [{ say: 'I have a brother.', opts: ['I have a brother.', 'I have a sister.', 'I have a robot.'] },
      { say: 'This is my mum.', opts: ['This is my mum.', 'This is my dad.', 'This is my baby.'] },
      { say: 'I am seven.', opts: ['I am seven.', 'I am eleven.', 'I am six.'] }] },
  { id: 'a2', world: 0, req: 10, icon: '🐾', title: 'Мои питомцы', intro: 'Девочка рассказывает о своих питомцах. Слушай внимательно!',
    text: [{ en: 'I have a cat.', ru: 'У меня есть кошка.' }, { en: 'The cat is black.', ru: 'Кошка чёрная.' }, { en: 'I have a dog.', ru: 'У меня есть собака.' },
      { en: 'The dog is white.', ru: 'Собака белая.' }, { en: 'I like my pets.', ru: 'Я люблю своих питомцев.' }],
    qs: [{ en: 'What colour is the cat?', ru: 'Какого цвета кошка?', ans: 'Black', opts: ['Black', 'White', 'Red'] },
      { en: 'What colour is the dog?', ru: 'Какого цвета собака?', ans: 'White', opts: ['White', 'Yellow', 'Green'] },
      { en: 'What pets has she got?', ru: 'Какие у неё питомцы?', ans: 'A cat and a dog', opts: ['A cat and a dog', 'A frog and a bird', 'A mouse and a horse'] }],
    pick: [{ say: 'The cat is black.', opts: ['The cat is black.', 'The cat is white.', 'The dog is black.'] },
      { say: 'I have a dog.', opts: ['I have a dog.', 'I have a frog.', 'I have a doll.'] },
      { say: 'I like my pets.', opts: ['I like my pets.', 'I like my toys.', 'I like my pizza.'] }] },
  { id: 'a3', world: 0, req: 13, icon: '👕', title: 'Что на мне', intro: 'Робот описывает свою одежду. Запоминай цвета!',
    text: [{ en: 'Look at me!', ru: 'Посмотри на меня!' }, { en: 'I have a red hat.', ru: 'У меня красная шляпа.' }, { en: 'I have blue jeans.', ru: 'У меня синие джинсы.' },
      { en: 'I have green socks.', ru: 'У меня зелёные носки.' }, { en: 'I have yellow shoes.', ru: 'У меня жёлтые ботинки.' }],
    qs: [{ en: 'What colour is the hat?', ru: 'Какого цвета шляпа?', ans: 'Red', opts: ['Red', 'Blue', 'Green'] },
      { en: 'What colour are the jeans?', ru: 'Какого цвета джинсы?', ans: 'Blue', opts: ['Blue', 'Black', 'Pink'] },
      { en: 'What colour are the shoes?', ru: 'Какого цвета ботинки?', ans: 'Yellow', opts: ['Yellow', 'White', 'Red'] }],
    pick: [{ say: 'I have green socks.', opts: ['I have green socks.', 'I have blue socks.', 'I have green shoes.'] },
      { say: 'I have a red hat.', opts: ['I have a red hat.', 'I have a red cat.', 'I have a pink hat.'] },
      { say: 'I have blue jeans.', opts: ['I have blue jeans.', 'I have black jeans.', 'I have blue shirt.'] }] },

  { id: 'a4', world: 1, req: 22, icon: '🏫', title: 'Мой понедельник', intro: 'Мальчик рассказывает, как проходит его день. Слушай!',
    text: [{ en: 'Today is Monday.', ru: 'Сегодня понедельник.' }, { en: 'I go to school.', ru: 'Я иду в школу.' }, { en: 'I have English and art.', ru: 'У меня английский и рисование.' },
      { en: 'I like English.', ru: 'Я люблю английский.' }, { en: 'After school I play football.', ru: 'После школы я играю в футбол.' }],
    qs: [{ en: 'What day is it?', ru: 'Какой сегодня день?', ans: 'Monday', opts: ['Monday', 'Friday', 'Sunday'] },
      { en: 'What does he like?', ru: 'Что он любит?', ans: 'English', opts: ['English', 'Maths', 'Music'] },
      { en: 'What does he do after school?', ru: 'Что он делает после школы?', ans: 'Plays football', opts: ['Plays football', 'Watches TV', 'Sleeps'] }],
    pick: [{ say: 'Today is Monday.', opts: ['Today is Monday.', 'Today is Sunday.', 'Today is Friday.'] },
      { say: 'I go to school.', opts: ['I go to school.', 'I go to the park.', 'I go to bed.'] },
      { say: 'After school I play football.', opts: ['After school I play football.', 'After school I watch TV.', 'Before school I play football.'] }] },
  { id: 'a5', world: 1, req: 24, icon: '🏠', title: 'Мой дом', intro: 'Девочка показывает свой дом. Слушай внимательно!',
    text: [{ en: 'This is my house.', ru: 'Это мой дом.' }, { en: 'It is big.', ru: 'Он большой.' }, { en: 'There is a kitchen and a bedroom.', ru: 'Тут есть кухня и спальня.' },
      { en: 'There is a garden too.', ru: 'А ещё есть сад.' }, { en: 'In the garden there are two cats.', ru: 'В саду две кошки.' }],
    qs: [{ en: 'Is the house big or small?', ru: 'Дом большой или маленький?', ans: 'Big', opts: ['Big', 'Small', 'Very small'] },
      { en: 'What is in the house?', ru: 'Что есть в доме?', ans: 'A kitchen and a bedroom', opts: ['A kitchen and a bedroom', 'A school and a park', 'A shop and a bank'] },
      { en: 'How many cats are in the garden?', ru: 'Сколько кошек в саду?', ans: 'Two', opts: ['Two', 'One', 'Three'] }],
    pick: [{ say: 'There is a garden too.', opts: ['There is a garden too.', 'There is a car too.', 'There are two gardens.'] },
      { say: 'In the garden there are two cats.', opts: ['In the garden there are two cats.', 'In the garden there is one cat.', 'In the kitchen there are two cats.'] },
      { say: 'This is my house.', opts: ['This is my house.', 'This is my horse.', 'This is my mouse.'] }] },
  { id: 'a6', world: 1, req: 29, icon: '🦒', title: 'В зоопарке', intro: 'Ребёнок гуляет по зоопарку. Каких зверей он видит?',
    text: [{ en: 'We are at the zoo.', ru: 'Мы в зоопарке.' }, { en: 'I see a tall giraffe.', ru: 'Я вижу высокого жирафа.' }, { en: 'I see a green snake.', ru: 'Я вижу зелёную змею.' },
      { en: "The snake can't run.", ru: 'Змея не умеет бегать.' }, { en: 'I like the panda!', ru: 'Мне нравится панда!' }],
    qs: [{ en: 'Where are they?', ru: 'Где они?', ans: 'At the zoo', opts: ['At the zoo', 'At school', 'At home'] },
      { en: 'Which animal is tall?', ru: 'Какое животное высокое?', ans: 'The giraffe', opts: ['The giraffe', 'The snake', 'The panda'] },
      { en: 'What colour is the snake?', ru: 'Какого цвета змея?', ans: 'Green', opts: ['Green', 'Red', 'Black'] },
      { en: 'Which animal does he like?', ru: 'Какое животное ему нравится?', ans: 'The panda', opts: ['The panda', 'The tiger', 'The bear'] }],
    pick: [{ say: 'I see a tall giraffe.', opts: ['I see a tall giraffe.', 'I see a small giraffe.', 'I see a tall tiger.'] },
      { say: "The snake can't run.", opts: ["The snake can't run.", 'The snake can run.', "The snake can't swim."] },
      { say: 'I like the panda!', opts: ['I like the panda!', 'I like the parrot!', 'I like the pizza!'] }] },

  { id: 'a7', world: 2, req: 41, icon: '🗻', title: 'Привет из Японии', intro: 'Пришло голосовое сообщение от друга из путешествия!',
    text: [{ en: 'Hello from Japan!', ru: 'Привет из Японии!' }, { en: 'It is sunny today.', ru: 'Сегодня солнечно.' }, { en: 'We went by plane.', ru: 'Мы прилетели на самолёте.' },
      { en: 'Yesterday we saw a volcano.', ru: 'Вчера мы видели вулкан.' }, { en: 'It was very big.', ru: 'Он был очень большой.' }],
    qs: [{ en: 'Where is he?', ru: 'Где он?', ans: 'In Japan', opts: ['In Japan', 'In Egypt', 'In France'] },
      { en: 'What is the weather like?', ru: 'Какая погода?', ans: 'Sunny', opts: ['Sunny', 'Rainy', 'Windy'] },
      { en: 'How did they travel?', ru: 'Как они добрались?', ans: 'By plane', opts: ['By plane', 'By bus', 'By ship'] },
      { en: 'What did they see yesterday?', ru: 'Что они видели вчера?', ans: 'A volcano', opts: ['A volcano', 'A museum', 'A river'] }],
    pick: [{ say: 'We went by plane.', opts: ['We went by plane.', 'We go by plane.', 'We went by train.'] },
      { say: 'Yesterday we saw a volcano.', opts: ['Yesterday we saw a volcano.', 'Today we see a volcano.', 'Yesterday we saw a mountain.'] },
      { say: 'It was very big.', opts: ['It was very big.', 'It is very big.', 'It was very small.'] }] },
  { id: 'a8', world: 2, req: 48, icon: '📺', title: 'Суббота Макса', intro: 'Макс рассказывает, как провёл вчерашний день.',
    text: [{ en: 'Yesterday was Saturday.', ru: 'Вчера была суббота.' }, { en: "I got up at nine o'clock.", ru: 'Я встал в девять часов.' }, { en: 'I ate breakfast and played football.', ru: 'Я позавтракал и поиграл в футбол.' },
      { en: 'In the evening I watched TV.', ru: 'Вечером я смотрел телевизор.' }, { en: 'I went to bed at ten.', ru: 'Я лёг спать в десять.' }],
    qs: [{ en: 'What day was yesterday?', ru: 'Какой день был вчера?', ans: 'Saturday', opts: ['Saturday', 'Sunday', 'Monday'] },
      { en: 'What time did he get up?', ru: 'Во сколько он встал?', ans: 'At nine', opts: ['At nine', 'At seven', 'At ten'] },
      { en: 'What did he do in the evening?', ru: 'Что он делал вечером?', ans: 'He watched TV', opts: ['He watched TV', 'He played football', 'He read a book'] }],
    pick: [{ say: "I got up at nine o'clock.", opts: ["I got up at nine o'clock.", "I get up at nine o'clock.", "I got up at seven o'clock."] },
      { say: 'I ate breakfast and played football.', opts: ['I ate breakfast and played football.', 'I ate lunch and played football.', 'I ate breakfast and watched TV.'] },
      { say: 'I went to bed at ten.', opts: ['I went to bed at ten.', 'I went to bed at nine.', 'I go to bed at ten.'] }] },
  { id: 'a9', world: 2, req: 50, icon: '🎂', title: 'День рождения', intro: 'Сегодня у друга праздник! Послушай, как он его празднует.',
    text: [{ en: 'Today is my birthday!', ru: 'Сегодня мой день рождения!' }, { en: 'I am ten.', ru: 'Мне десять.' }, { en: 'We have a party.', ru: 'У нас вечеринка.' },
      { en: 'I have a big cake with ten candles.', ru: 'У меня большой торт с десятью свечами.' }, { en: 'My friends give me presents.', ru: 'Друзья дарят мне подарки.' }, { en: 'I am very happy.', ru: 'Я очень счастлив.' }],
    qs: [{ en: 'What is today?', ru: 'Какой сегодня день?', ans: 'His birthday', opts: ['His birthday', 'Christmas', 'Sunday'] },
      { en: 'How old is he?', ru: 'Сколько ему лет?', ans: 'Ten', opts: ['Ten', 'Nine', 'Eleven'] },
      { en: 'What is on the cake?', ru: 'Что на торте?', ans: 'Ten candles', opts: ['Ten candles', 'Two candles', 'A robot'] },
      { en: 'How does he feel?', ru: 'Что он чувствует?', ans: 'Happy', opts: ['Happy', 'Sad', 'Angry'] }],
    pick: [{ say: 'We have a party.', opts: ['We have a party.', 'We have a pizza.', 'We had a party.'] },
      { say: 'My friends give me presents.', opts: ['My friends give me presents.', 'My friends gave me presents.', 'My friends give me cakes.'] },
      { say: 'I have a big cake with ten candles.', opts: ['I have a big cake with ten candles.', 'I have a big cake with two candles.', 'I have a small cake with ten candles.'] }] }
];
