/* Итальянский язык: слова и уроки Мира 1 («Primi passi»). Данные устроены так же, как у английского (поле en хранит итальянский текст),
   поэтому все режимы игры (слова, аудирование, диалоги, песенки, карточки) работают без изменений. Номера уроков 501–599. */
const IT_WORDS = {};
const itId = s => 'it_' + s.toLowerCase().normalize('NFD').replace(/[̀-ͯ]/g, '').replace(/[^a-z0-9]+/g, '_').replace(/^_|_$/g, '');
// слово: «итальянский|русский|эмодзи|буква азбуки»; без «|» — ссылка на уже описанное слово
const wi = spec => {
  if (!spec.includes('|')) { const id = itId(spec); if (!IT_WORDS[id]) throw new Error('нет слова ' + spec); return id; }
  const [it, ru, e, L] = spec.split('|'), id = itId(it); IT_WORDS[id] = { id, en: it, ru, e, L: L || '' }; return id;
};
const IS = a => (a || []).map(s => { const [en, ru] = s.split('|'); return { en, ru }; });
const GP = spec => { const [en, ans, opts, ru] = spec.split('|'); return { en, ans, opts: opts.split('/'), ru }; };
// урок со словами
const LW = (id, icon, title, story, words, sents) => ({ id, title, icon, words: words.map(wi), story, sents: IS(sents) });
// урок по грамматике: правило + пропуски
const LG = (id, icon, title, story, rt, rhtml, ex, gaps, sents) => ({ id, title, icon, type: 'gram', story, rule: { title: rt, html: rhtml, ex: ex.map(s => s.split('|')) }, gaps: gaps.map(GP), sents: IS(sents) });
// чтение: текст, вопросы «вопрос|перевод|ответ|вариант|вариант», порядок событий (индексы строк), предложения для сборки
const LR = (id, icon, title, story, text, qs, order, sents) => ({ id, title, icon, type: 'read', story, nextLabel: 'Вопросы по тексту ➜', text: IS(text),
  qs: qs.map(q => { const [en, ru, ans, o2, o3] = q.split('|'); return { en, ru, ans, opts: [ans, o2, o3].filter(Boolean) }; }), order, sents: IS(sents) });

const IT_L1 = [
  LW(501, '👋', 'Ciao!', 'Ты попал в страну вкусной пасты и музыки! Злой Диментикон украл итальянские слова. Начнём с приветствий.',
    ['ciao|привет, пока|👋', 'arrivederci|до свидания|🚪', 'sì|да|✅', 'no|нет|❌', 'grazie|спасибо|🙏', 'prego|пожалуйста|🤝', 'scusa|извини|😔', 'per favore|пожалуйста (просьба)|🥺'],
    ['Ciao, mi chiamo Marco.|Привет, меня зовут Марко.', 'Come stai?|Как дела?', 'Sto bene, grazie.|У меня всё хорошо, спасибо.']),
  LW(502, '🐝', 'Алфавит A–E', 'Итальянский алфавит поёт! В нём 21 буква. Найди первые пять в пчелином саду.',
    ['ape|пчела|🐝|A', 'barca|лодка|⛵|B', 'casa|дом|🏠|C', 'dado|игральная кость|🎲|D', 'elefante|слон|🐘|E'],
    ['Questa è una casa.|Это дом.', 'Vedo un elefante.|Я вижу слона.', 'La barca è blu.|Лодка синяя.']),
  LW(503, '🌸', 'Алфавит F–L', 'Буквы F–L спрятались на острове цветов. Слово «hotel» читается без буквы H!',
    ['fiore|цветок|🌸|F', 'gatto|кот|🐱|G', 'hotel|отель|🏨|H', 'isola|остров|🏝️|I', 'luna|луна|🌙|L'],
    ['Il gatto è sull’isola.|Кот на острове.', 'Vedo la luna.|Я вижу луну.', 'Ecco un fiore!|Вот цветок!']),
  LW(504, '🍎', 'Алфавит M–R', 'В итальянском нет букв J, K, W, X, Y — они только в иностранных словах. Найди M–R.',
    ['mela|яблоко|🍎|M', 'naso|нос|👃|N', 'occhio|глаз|👁️|O', 'pane|хлеб|🍞|P', 'quadro|картина|🖼️|Q', 'riso|рис|🍚|R'],
    ['Mangio una mela.|Я ем яблоко.', 'Ho un naso piccolo.|У меня маленький нос.', 'Il pane è buono.|Хлеб вкусный.']),
  LW(505, '☀️', 'Алфавит S–Z', 'Последние буквы мира: S, T, U, V, Z.',
    ['sole|солнце|☀️|S', 'torta|торт|🎂|T', 'uva|виноград|🍇|U', 'volpe|лиса|🦊|V', 'zebra|зебра|🦓|Z'],
    ['Il sole è giallo.|Солнце жёлтое.', 'Mi piace la torta.|Мне нравится торт.', 'La volpe è furba.|Лиса хитрая.']),
  LW(506, '🔢', 'Числа 1–10', 'В шахте итальянских чисел Диментикон спрятал цифры от одного до десяти.',
    ['uno|1|1️⃣', 'due|2|2️⃣', 'tre|3|3️⃣', 'quattro|4|4️⃣', 'cinque|5|5️⃣', 'sei|6|6️⃣', 'sette|7|7️⃣', 'otto|8|8️⃣', 'nove|9|9️⃣', 'dieci|10|🔟'],
    ['Ho due gatti.|У меня два кота.', 'Ho sei anni.|Мне шесть лет.', 'Conto fino a dieci.|Я считаю до десяти.']),
  LW(507, '🔟', 'Числа 11–20', 'Дальше — от одиннадцати до двадцати. Почти все числа заканчиваются на -dici.',
    ['undici|11|11', 'dodici|12|12', 'tredici|13|13', 'quattordici|14|14', 'quindici|15|15', 'sedici|16|16', 'diciassette|17|17', 'diciotto|18|18', 'diciannove|19|19', 'venti|20|20'],
    ['Ho dodici matite.|У меня двенадцать карандашей.', 'Mia sorella ha quindici anni.|Моей сестре пятнадцать лет.', 'Venti è un bel numero.|Двадцать — красивое число.']),
  LW(508, '🌈', 'Colori', 'Диментикон выкрасил Италию в серый цвет. Верни краски!',
    ['rosso|красный|🟥', 'blu|синий|🟦', 'verde|зелёный|🟩', 'giallo|жёлтый|🟨', 'arancione|оранжевый|🟧', 'rosa|розовый|🩷', 'nero|чёрный|⬛', 'bianco|белый|⬜'],
    ['La mela è rossa.|Яблоко красное.', 'Il cielo è blu.|Небо синее.', 'Mi piace il verde.|Мне нравится зелёный.']),
  LW(509, '👨‍👩‍👧', 'La famiglia', 'В доме собралась вся итальянская семья. Поздоровайся с каждым!',
    ['mamma|мама|👩', 'papà|папа|👨', 'fratello|брат|👦', 'sorella|сестра|👧', 'nonna|бабушка|👵', 'nonno|дедушка|👴', 'bambino|малыш, ребёнок|👶'],
    ['Questa è la mia mamma.|Это моя мама.', 'Ho un fratello.|У меня есть брат.', 'Il nonno è simpatico.|Дедушка приятный.']),
  LW(510, '🧸', 'Giocattoli', 'В мастерской роботы собирают игрушки. Названия забыты!',
    ['robot|робот|🤖', 'macchina|машина|🚗', 'treno|поезд|🚂', 'bicicletta|велосипед|🚲', 'bambola|кукла|🪆', 'orsacchiotto|плюшевый мишка|🧸', 'palla|мяч|⚽'],
    ['Ho un robot.|У меня есть робот.', 'La palla è rotonda.|Мяч круглый.', 'Gioco con il treno.|Я играю с поездом.']),
  LW(511, '🐾', 'Gli animali', 'Домашние питомцы сбежали. Назови их — и они вернутся.',
    ['cane|собака|🐶', 'uccello|птица|🐦', 'topo|мышь|🐭', 'coniglio|кролик|🐰', 'rana|лягушка|🐸', 'cavallo|лошадь|🐴', 'gatto'],
    ['Il cane abbaia.|Собака лает.', 'Il gatto beve il latte.|Кот пьёт молоко.', 'Il coniglio salta.|Кролик прыгает.']),
  LW(512, '🧍', 'Il corpo', 'Робот-учёный собирает нового робота. Подскажи названия частей тела.',
    ['occhi|глаза|👀', 'orecchie|уши|👂', 'naso', 'bocca|рот|👄', 'mano|рука (кисть)|✋', 'gamba|нога|🦵', 'piede|стопа|🦶'],
    ['Ho due occhi.|У меня два глаза.', 'Apro la bocca.|Я открываю рот.', 'Ho un piede grande.|У меня большая ступня.']),
  LW(513, '🥖', 'Il cibo', 'Из пекарни пахнет вкусным! Только ценники пропали.',
    ['pane', 'latte|молоко|🥛', 'torta', 'pizza|пицца|🍕', 'banana|банан|🍌', 'mela', 'succo|сок|🧃'],
    ['Bevo il latte.|Я пью молоко.', 'La pizza è buona.|Пицца вкусная.', 'Mangio una banana.|Я ем банан.']),
  LW(514, '👚', 'I vestiti', 'Диментикон перемешал всю одежду. Разложи её по названиям.',
    ['cappello|шляпа, шапка|🎩', 'scarpe|ботинки|👟', 'calzini|носки|🧦', 'vestito|платье|👗', 'jeans|джинсы|👖', 'camicia|рубашка|👕', 'giacca|куртка|🧥'],
    ['Metto il cappello.|Я надеваю шляпу.', 'Le scarpe sono nuove.|Ботинки новые.', 'Ho una giacca rossa.|У меня красная куртка.']),
  LW(515, '🏠', 'La casa', 'Ты нашёл свой первый итальянский дом. Расставим мебель!',
    ['casa', 'letto|кровать|🛏️', 'sedia|стул|🪑', 'divano|диван|🛋️', 'lampada|лампа|💡', 'tavolo|стол|🍽️', 'finestra|окно|🪟'],
    ['Questa è la mia casa.|Это мой дом.', 'La lampada è sul tavolo.|Лампа на столе.', 'Sono sul divano.|Я на диване.']),
  LW(516, '🎂', 'Il compleanno', 'Сегодня праздник! Подготовь вечеринку.',
    ['compleanno|день рождения|🥳', 'palloncino|воздушный шарик|🎈', 'regalo|подарок|🎁', 'candela|свеча|🕯️', 'festa|праздник, вечеринка|🎉', 'torta'],
    ['Buon compleanno!|С днём рождения!', 'Quanti anni hai?|Сколько тебе лет?', 'Ho otto anni.|Мне восемь лет.']),
  LW(517, '📅', 'I giorni', 'Календарь Диментикона рассыпался. Собери дни недели.',
    ['lunedì|понедельник|1', 'martedì|вторник|2', 'mercoledì|среда|3', 'giovedì|четверг|4', 'venerdì|пятница|5', 'sabato|суббота|6', 'domenica|воскресенье|7'],
    ['Oggi è lunedì.|Сегодня понедельник.', 'Sabato vado al parco.|В субботу я иду в парк.', 'La domenica riposo.|В воскресенье я отдыхаю.']),
  LW(518, '⛅', 'Il tempo', 'Какая сегодня погода? Узнай у жителей острова.',
    ['sole', 'pioggia|дождь|🌧️', 'neve|снег|❄️', 'vento|ветер|💨', 'nuvola|облако|☁️', 'caldo|жарко|🥵', 'freddo|холодно|🥶'],
    ['Oggi c’è il sole.|Сегодня солнечно.', 'Fa freddo.|Холодно.', 'Piove.|Идёт дождь.']),
  LW(519, '🏃', 'Le azioni', 'Герои хвастаются, что умеют делать. Угадай глаголы!',
    ['correre|бегать|🏃', 'saltare|прыгать|🤸', 'nuotare|плавать|🏊', 'volare|летать|🕊️', 'cantare|петь|🎤', 'ballare|танцевать|💃', 'giocare|играть|🎮'],
    ['Mi piace correre.|Мне нравится бегать.', 'Gli uccelli volano.|Птицы летают.', 'Noi cantiamo.|Мы поём.']),
  LW(520, '😊', 'I saluti', 'В Италии здороваются по-разному в течение дня.',
    ['buongiorno|добрый день|🌞', 'buonasera|добрый вечер|🌆', 'buonanotte|спокойной ночи|🌙', 'bene|хорошо|👍', 'male|плохо|👎', 'Come stai?|Как дела?|😊'],
    ['Buongiorno, signora!|Добрый день, синьора!', 'Buonanotte, mamma.|Спокойной ночи, мама.', 'Sto bene, e tu?|У меня хорошо, а у тебя?']),
  LG(521, '🧑', 'Io sono…', 'Давай расскажем, кто мы. Для этого нужен глагол essere — «быть».',
    'essere — «быть»', '<ul><li><b>io sono</b> — я</li><li><b>tu sei</b> — ты</li><li><b>lui/lei è</b> — он/она</li><li><b>noi siamo</b> — мы</li><li><b>voi siete</b> — вы</li><li><b>loro sono</b> — они</li></ul>',
    ['Io sono Marco.|Я Марко.', 'Tu sei alto.|Ты высокий.', 'Lei è Anna.|Она Анна.'],
    ['Io ___ un bambino.|sono|sono/sei/è|Я ребёнок.', 'Tu ___ simpatico.|sei|sono/sei/è|Ты симпатичный.', 'Lei ___ la mia mamma.|è|sono/sei/è|Она моя мама.', 'Noi ___ amici.|siamo|siamo/siete/sono|Мы друзья.',
     'Voi ___ a scuola.|siete|siamo/siete/sono|Вы в школе.', 'Loro ___ felici.|sono|è/siete/sono|Они счастливы.', 'Lui ___ il mio fratello.|è|è/sei/siamo|Он мой брат.', 'Io ___ italiano.|sono|sei/sono/è|Я итальянец.'],
    ['Io sono felice.|Я счастлив.', 'Tu sei il mio amico.|Ты мой друг.', 'Noi siamo a casa.|Мы дома.']),
  LG(522, '👋', 'Mi chiamo…', 'Знакомство! Как зовут, сколько лет, откуда.',
    'Знакомство', '<ul><li><b>Come ti chiami?</b> — Как тебя зовут?</li><li><b>Mi chiamo Anna.</b> — Меня зовут Анна.</li><li><b>Quanti anni hai?</b> — Сколько тебе лет?</li><li><b>Ho nove anni.</b> — Мне девять лет.</li></ul>',
    ['Come ti chiami?|Как тебя зовут?', 'Mi chiamo Luca.|Меня зовут Лука.', 'Ho otto anni.|Мне восемь лет.'],
    ['Come ti ___?|chiami|chiami/chiamo/chiama|Как тебя зовут?', 'Mi ___ Anna.|chiamo|chiami/chiamo/chiama|Меня зовут Анна.', 'Quanti anni ___?|hai|hai/ho/ha|Сколько тебе лет?', 'Ho ___ anni.|nove|nove/nave/neve|Мне девять лет.',
     'Piacere, ___ Luca.|sono|sono/hai/ho|Приятно познакомиться, я Лука.', 'Di dove ___?|sei|sei/ho/hai|Откуда ты?', 'Sono ___ Roma.|di|di/in/con|Я из Рима.', 'Lui si ___ Paolo.|chiama|chiamo/chiama/chiami|Его зовут Паоло.'],
    ['Mi chiamo Sofia.|Меня зовут София.', 'Ho sette anni.|Мне семь лет.', 'Piacere di conoscerti!|Приятно познакомиться!']),
  LW(524, '🎒', 'La scuola', 'Звонок! Собери рюкзак для школы.',
    ['scuola|школа|🏫', 'libro|книга|📘', 'quaderno|тетрадь|📓', 'penna|ручка|🖊️', 'matita|карандаш|✏️', 'zaino|рюкзак|🎒', 'banco|парта|🪑'],
    ['Il libro è sul banco.|Книга на парте.', 'Ho una penna blu.|У меня синяя ручка.', 'Vado a scuola.|Я иду в школу.']),
  LG(523, '🅰️', 'Un, una', 'Все слова в итальянском — мужского или женского рода. Перед ними ставят un или una.',
    'Артикли un / una', '<ul><li><b>un</b> — перед словами мужского рода: <i>un gatto, un libro</i></li><li><b>una</b> — перед словами женского рода: <i>una casa, una mela</i></li></ul><p>Слова на -o обычно мужского рода, на -a — женского.</p>',
    ['un gatto|кот', 'una casa|дом', 'un libro|книга'],
    ['Ho ___ gatto.|un|un/una|У меня есть кот.', 'Ho ___ casa.|una|un/una|У меня есть дом.', 'Questo è ___ libro.|un|un/una|Это книга.', 'Lei ha ___ penna.|una|un/una|У неё есть ручка.',
     'È ___ amico.|un|un/una|Это друг.', 'È ___ amica.|una|un/una|Это подруга.', 'Vedo ___ albero.|un|un/una|Я вижу дерево.', 'Mangio ___ mela.|una|un/una|Я ем яблоко.'],
    ['Ho un cane.|У меня есть собака.', 'Vedo una luna.|Я вижу луну.', 'È un bel giorno.|Это прекрасный день.']),
  LW(525, '🍊', 'La frutta', 'В корзинке Диментикона фрукты без названий.',
    ['arancia|апельсин|🍊', 'limone|лимон|🍋', 'pesca|персик|🍑', 'fragola|клубника|🍓', 'ciliegia|вишня|🍒', 'pera|груша|🍐', 'uva'],
    ['Mi piace la fragola.|Мне нравится клубника.', 'Il limone è giallo.|Лимон жёлтый.', 'Mangio una pera.|Я ем грушу.']),
  LG(526, '2️⃣', 'Una, due: plurale', 'Один — это un gatto, а два? Меняем окончание!',
    'Множественное число', '<ul><li>-<b>o</b> → -<b>i</b>: <i>un gatto → due gatti</i></li><li>-<b>a</b> → -<b>e</b>: <i>una casa → due case</i></li><li>-<b>e</b> → -<b>i</b>: <i>un fiore → due fiori</i></li></ul>',
    ['un gatto — due gatti|кот — два кота', 'una casa — due case|дом — два дома', 'una mela — tre mele|яблоко — три яблока'],
    ['Ho due gatt___.|i|i/e/a|У меня два кота.', 'Ho tre cas___.|e|i/e/o|У меня три дома.', 'Ecco due libr___.|i|i/e/o|Вот две книги.', 'Mangio due mel___.|e|i/e/o|Я ем два яблока.',
     'Vedo quattro fior___.|i|i/e/o|Я вижу четыре цветка.', 'Ho cinque matit___.|e|i/e/o|У меня пять карандашей.', 'Ci sono due cani, tre gatt___.|i|i/e/o|Есть две собаки и три кота.', 'Ho sei penn___.|e|i/e/o|У меня шесть ручек.'],
    ['Ho due fratelli.|У меня два брата.', 'Vedo tre case.|Я вижу три дома.', 'Ci sono due mele.|Тут два яблока.']),
  LW(527, '🔁', 'Ripasso 1', 'Перед боссом повторим слова из первых уроков!',
    ['ciao', 'gatto', 'casa', 'mela', 'sole', 'rosso', 'mamma', 'cane', 'pane', 'scuola'],
    ['Ciao! Come stai?|Привет! Как дела?', 'Il gatto mangia il pane.|Кот ест хлеб.', 'Il sole è giallo.|Солнце жёлтое.']),
  LW(528, '🧩', 'Piccole frasi', 'Вежливые слова и простые фразы — как в настоящем Риме.',
    ['Mi chiamo|меня зовут|👋', 'Ho fame|я голоден|🤤', 'Ho sete|я хочу пить|🥤', 'Sono felice|я счастлив|😄', 'Sono stanco|я устал|😴', 'Ho paura|мне страшно|😨'],
    ['Ho fame, mamma!|Я голоден, мама!', 'Sono felice oggi.|Сегодня я счастлив.', 'Ho paura del buio.|Я боюсь темноты.'])
];
const IT_BOSS1 = { id: 590, title: 'Castello del Dimenticone', icon: '🏰', bossIcon: '🧙' };
