/* Итальянский: Мир 2 «La mia vita» (уроки 531–561). */
const IT_L2 = [
  LW(531, '🔢', 'Числа 30–100', 'Считаем десятками, как настоящие итальянские торговцы.',
    ['trenta|30|30', 'quaranta|40|40', 'cinquanta|50|50', 'sessanta|60|60', 'settanta|70|70', 'ottanta|80|80', 'novanta|90|90', 'cento|100|100'],
    ['Ho cinquanta euro.|У меня пятьдесят евро.', 'Mio nonno ha settanta anni.|Моему дедушке семьдесят лет.', 'Cento è un numero grande.|Сто — большое число.']),
  LW(532, '🏙️', 'In città', 'Прогуляемся по итальянскому городу и найдём важные места.',
    ['parco|парк|🌳', 'negozio|магазин|🏪', 'bar|бар, кафе|☕', 'stazione|вокзал|🚉', 'ospedale|больница|🏥', 'chiesa|церковь|⛪', 'piazza|площадь|🏛️'],
    ['Vado al parco.|Я иду в парк.', 'La stazione è grande.|Вокзал большой.', 'In piazza c’è una fontana.|На площади есть фонтан.']),
  LW(533, '🗓️', 'I mesi', 'Двенадцать месяцев ждут тебя. Собери календарь!',
    ['gennaio|январь|Янв', 'febbraio|февраль|Фев', 'marzo|март|Мар', 'aprile|апрель|Апр', 'maggio|май|Май', 'giugno|июнь|Июн', 'luglio|июль|Июл', 'agosto|август|Авг', 'settembre|сентябрь|Сен', 'ottobre|октябрь|Окт', 'novembre|ноябрь|Ноя', 'dicembre|декабрь|Дек'],
    ['Il mio compleanno è a maggio.|Мой день рождения в мае.', 'A dicembre fa freddo.|В декабре холодно.', 'Luglio è caldo.|Июль жаркий.']),
  LW(534, '🌤️', 'Le stagioni', 'Времена года в Италии очень разные: от снега в горах до жаркого моря.',
    ['primavera|весна|🌸', 'estate|лето|☀️', 'autunno|осень|🍂', 'inverno|зима|❄️', 'stagione|время года|🌦️', 'anno|год|📆', 'mese|месяц|🗓️'],
    ['In estate vado al mare.|Летом я еду на море.', 'In inverno nevica.|Зимой идёт снег.', 'La primavera è bella.|Весна прекрасна.']),
  LW(535, '📚', 'Le materie', 'В итальянской школе много предметов. Какие тебе нравятся?',
    ['italiano|итальянский язык|🇮🇹', 'matematica|математика|➗', 'arte|рисование|🎨', 'musica|музыка|🎵', 'scienze|природоведение|🔬', 'geografia|география|🌍', 'storia|история|📜', 'ginnastica|физкультура|🤸'],
    ['Mi piace la matematica.|Мне нравится математика.', 'Oggi ho arte e musica.|Сегодня у меня рисование и музыка.', 'La ginnastica è divertente.|Физкультура весёлая.']),
  LW(536, '⚽', 'Lo sport', 'Итальянцы обожают спорт. Назови любимые игры!',
    ['calcio|футбол|⚽', 'tennis|теннис|🎾', 'nuoto|плавание|🏊', 'pallavolo|волейбол|🏐', 'pallacanestro|баскетбол|🏀', 'sci|лыжи|⛷️', 'ciclismo|велоспорт|🚴'],
    ['Gioco a calcio.|Я играю в футбол.', 'Il nuoto è bello.|Плавание — это здорово.', 'Mi piace il tennis.|Мне нравится теннис.']),
  LW(537, '🍝', 'Il cibo (2)', 'В итальянской кухне столько вкусного! Разберись, что есть что.',
    ['pasta|макароны, паста|🍝', 'formaggio|сыр|🧀', 'prosciutto|ветчина|🥓', 'gelato|мороженое|🍦', 'cioccolato|шоколад|🍫', 'biscotti|печенье|🍪', 'uova|яйца|🥚', 'acqua|вода|💧'],
    ['Mangio la pasta.|Я ем пасту.', 'Il gelato è freddo.|Мороженое холодное.', 'Bevo l’acqua.|Я пью воду.']),
  LW(538, '🥕', 'La verdura', 'На рынке Диментикона овощи без ценников. Разложи по названиям.',
    ['pomodoro|помидор|🍅', 'patata|картофель|🥔', 'carota|морковь|🥕', 'cipolla|лук|🧅', 'insalata|салат|🥗', 'zucchina|кабачок|🥒'],
    ['Il pomodoro è rosso.|Помидор красный.', 'Mangio la carota.|Я ем морковь.', 'L’insalata è verde.|Салат зелёный.']),
  LW(539, '🦁', 'Lo zoo', 'Зоопарк ждёт гостей. Узнай всех зверей!',
    ['leone|лев|🦁', 'scimmia|обезьяна|🐒', 'tigre|тигр|🐯', 'giraffa|жираф|🦒', 'orso|медведь|🐻', 'delfino|дельфин|🐬', 'balena|кит|🐋', 'elefante'],
    ['Il leone è forte.|Лев сильный.', 'La giraffa è alta.|Жираф высокий.', 'Il delfino nuota.|Дельфин плавает.']),
  LW(540, '🐄', 'La fattoria', 'На ферме просыпаются животные. Кто как называется?',
    ['mucca|корова|🐄', 'maiale|свинья|🐷', 'pecora|овца|🐑', 'gallina|курица|🐔', 'anatra|утка|🦆', 'capra|коза|🐐', 'cavallo'],
    ['La mucca dà il latte.|Корова даёт молоко.', 'La gallina fa le uova.|Курица несёт яйца.', 'Il cavallo corre.|Лошадь бежит.']),
  LW(541, '👨‍🍳', 'I mestieri', 'Кем работают люди в городе?',
    ['medico|врач|👨‍⚕️', 'maestra|учительница|👩‍🏫', 'cuoco|повар|👨‍🍳', 'pompiere|пожарный|🧑‍🚒', 'poliziotto|полицейский|👮', 'pilota|лётчик|🧑‍✈️', 'panettiere|пекарь|🥖'],
    ['Mio padre è medico.|Мой папа врач.', 'La maestra è gentile.|Учительница добрая.', 'Il cuoco cucina la pasta.|Повар готовит пасту.']),
  LW(542, '🚌', 'I trasporti', 'Чем можно ехать в Италии? Выбери транспорт!',
    ['autobus|автобус|🚌', 'aereo|самолёт|✈️', 'nave|корабль|🚢', 'moto|мотоцикл|🏍️', 'taxi|такси|🚕', 'camion|грузовик|🚚', 'treno'],
    ['Prendo l’autobus.|Я еду на автобусе.', 'L’aereo vola in alto.|Самолёт летит высоко.', 'Il treno è veloce.|Поезд быстрый.']),
  LW(543, '🍳', 'Le stanze', 'Заглянем в разные комнаты итальянского дома.',
    ['cucina|кухня|🍳', 'bagno|ванная|🛁', 'camera|комната, спальня|🛏️', 'giardino|сад|🌷', 'porta|дверь|🚪', 'tetto|крыша|🏠', 'scala|лестница|🪜'],
    ['Mamma è in cucina.|Мама на кухне.', 'Il giardino è bello.|Сад красивый.', 'Apro la porta.|Я открываю дверь.']),
  LW(544, '👨‍👩‍👧‍👦', 'La famiglia (2)', 'У итальянцев большая семья. Познакомься с родственниками!',
    ['zio|дядя|🧔', 'zia|тётя|👩‍🦳', 'cugino|двоюродный брат|🧑', 'nipote|внук, племянник|👶', 'genitori|родители|👪', 'figlio|сын|👦', 'figlia|дочь|👧'],
    ['Lo zio è alto.|Дядя высокий.', 'La zia ha un figlio.|У тёти есть сын.', 'I miei genitori sono a casa.|Мои родители дома.']),
  LW(545, '↔️', 'Gli aggettivi', 'Слова-описания помогают рассказать, какие предметы и люди.',
    ['grande|большой|🐘', 'piccolo|маленький|🐭', 'nuovo|новый|✨', 'vecchio|старый|👴', 'bello|красивый|😍', 'brutto|некрасивый|😝', 'alto|высокий|🦒', 'basso|низкий|🐜'],
    ['Il cane è grande.|Собака большая.', 'La casa è vecchia.|Дом старый.', 'Il mio zaino è nuovo.|Мой рюкзак новый.']),
  LW(546, '📖', 'I verbi', 'Что мы делаем каждый день? Верни глаголы на место.',
    ['mangiare|есть|🍽️', 'bere|пить|🥤', 'dormire|спать|😴', 'leggere|читать|📖', 'scrivere|писать|✍️', 'guardare|смотреть|👀', 'ascoltare|слушать|👂', 'parlare|говорить|🗣️'],
    ['Mi piace leggere.|Мне нравится читать.', 'Il gatto dorme.|Кот спит.', 'Ascolto la musica.|Я слушаю музыку.']),
  LW(547, '🌅', 'La giornata', 'Распорядок дня: что и когда ты делаешь.',
    ['mattina|утро|🌅', 'pomeriggio|день (после обеда)|🌇', 'sera|вечер|🌆', 'notte|ночь|🌙', 'colazione|завтрак|🥐', 'pranzo|обед|🍝', 'cena|ужин|🍽️'],
    ['La mattina faccio colazione.|Утром я завтракаю.', 'A pranzo mangio la pasta.|На обед я ем пасту.', 'La sera guardo un film.|Вечером я смотрю фильм.']),
  LW(548, '🎨', 'I passatempi', 'Чем заняться на досуге? Выбери хобби!',
    ['disegnare|рисовать|🖌️', 'dipingere|писать красками|🎨', 'cucinare|готовить|🍳', 'suonare|играть на инструменте|🎸', 'passeggiare|гулять|🚶', 'viaggiare|путешествовать|🧳'],
    ['Mi piace disegnare.|Мне нравится рисовать.', 'Mia nonna cucina bene.|Моя бабушка хорошо готовит.', 'Suono la chitarra.|Я играю на гитаре.']),
  LG(549, '✋', 'Avere — «иметь»', 'С глаголом avere рассказывают, что у нас есть, и ещё сколько нам лет.',
    'avere — «иметь»', '<ul><li><b>io ho</b> — у меня</li><li><b>tu hai</b> — у тебя</li><li><b>lui/lei ha</b> — у него/неё</li><li><b>noi abbiamo</b> — у нас</li><li><b>voi avete</b> — у вас</li><li><b>loro hanno</b> — у них</li></ul>',
    ['Ho un cane.|У меня есть собака.', 'Hai fame?|Ты голоден?', 'Ha dieci anni.|Ему десять лет.'],
    ['Io ___ un cane.|ho|ho/hai/ha|У меня есть собака.', 'Tu ___ una sorella.|hai|ho/hai/ha|У тебя есть сестра.', 'Lui ___ fame.|ha|ho/hai/ha|Он голоден.', 'Noi ___ una casa.|abbiamo|abbiamo/avete/hanno|У нас есть дом.',
     'Voi ___ due gatti.|avete|abbiamo/avete/hanno|У вас два кота.', 'Loro ___ un giardino.|hanno|abbiamo/avete/hanno|У них есть сад.', 'Lei ___ dieci anni.|ha|ho/hai/ha|Ей десять лет.', 'Io ___ sete.|ho|ho/hai/ha|Я хочу пить.'],
    ['Ho un fratello.|У меня есть брат.', 'Abbiamo un cane.|У нас есть собака.', 'Hai una penna?|У тебя есть ручка?']),
  LG(550, '🅰️', 'Il, lo, la, l’', 'В итальянском перед словом стоит артикль. Нужный зависит от рода и первой буквы.',
    'Определённый артикль', '<ul><li><b>il</b> — мужской род: <i>il gatto, il libro</i></li><li><b>lo</b> — мужской род перед z, s+согласная: <i>lo zaino, lo studente</i></li><li><b>la</b> — женский род: <i>la casa, la mela</i></li><li><b>l’</b> — перед гласной: <i>l’amico, l’arancia</i></li></ul>',
    ['il gatto|кот', 'lo zaino|рюкзак', 'la casa|дом', 'l’amico|друг'],
    ['___ libro è rosso.|Il|Il/Lo/La|Книга красная.', '___ zaino è nuovo.|Lo|Il/Lo/La|Рюкзак новый.', '___ casa è grande.|La|Il/Lo/La|Дом большой.', '___ amico è alto.|L’|Il/L’/La|Друг высокий.',
     '___ arancia è dolce.|L’|La/L’/Lo|Апельсин сладкий.', '___ studente legge.|Lo|Il/Lo/La|Студент читает.', '___ gatto dorme.|Il|Il/Lo/La|Кот спит.', '___ penna è blu.|La|Il/Lo/La|Ручка синяя.'],
    ['Il gatto dorme.|Кот спит.', 'La mela è rossa.|Яблоко красное.', 'Lo zaino è pesante.|Рюкзак тяжёлый.', 'L’amico è simpatico.|Друг симпатичный.']),
  LG(551, '🗣️', 'Parlare, mangiare…', 'Большинство глаголов оканчиваются на -are. Меняем окончания!',
    'Глаголы на -are', '<ul><li><b>io</b> parl<b>o</b></li><li><b>tu</b> parl<b>i</b></li><li><b>lui/lei</b> parl<b>a</b></li><li><b>noi</b> parl<b>iamo</b></li><li><b>voi</b> parl<b>ate</b></li><li><b>loro</b> parl<b>ano</b></li></ul>',
    ['Io parlo italiano.|Я говорю по-итальянски.', 'Lei mangia la mela.|Она ест яблоко.', 'Noi giochiamo a calcio.|Мы играем в футбол.'],
    ['Io ___ italiano.|parlo|parlo/parli/parla|Я говорю по-итальянски.', 'Tu ___ molto.|parli|parlo/parli/parla|Ты много говоришь.', 'Lei ___ con la mamma.|parla|parlo/parli/parla|Она говорит с мамой.', 'Noi ___ in italiano.|parliamo|parliamo/parlate/parlano|Мы говорим по-итальянски.',
     'Voi ___ forte.|parlate|parliamo/parlate/parlano|Вы говорите громко.', 'Loro ___ russo.|parlano|parliamo/parlate/parlano|Они говорят по-русски.', 'Io ___ la musica.|ascolto|ascolto/ascolti/ascolta|Я слушаю музыку.', 'Marco ___ a calcio.|gioca|gioco/giochi/gioca|Марко играет в футбол.'],
    ['Mangio una mela.|Я ем яблоко.', 'Tu ascolti la musica.|Ты слушаешь музыку.', 'Loro giocano nel parco.|Они играют в парке.']),
  LG(552, '🎨', 'Il gatto nero, la casa nera', 'Прилагательные меняют окончание в зависимости от рода и числа.',
    'Согласование прилагательных', '<ul><li><i>il gatto <b>nero</b></i> (м. р., ед. ч.)</li><li><i>la casa <b>nera</b></i> (ж. р., ед. ч.)</li><li><i>i gatti <b>neri</b></i> (м. р., мн. ч.)</li><li><i>le case <b>nere</b></i> (ж. р., мн. ч.)</li></ul>',
    ['il gatto nero|чёрный кот', 'la casa bianca|белый дом', 'le mele rosse|красные яблоки'],
    ['Il gatto è ___.|nero|nero/nera/neri|Кот чёрный.', 'La casa è ___.|bianca|bianco/bianca/bianchi|Дом белый.', 'I libri sono ___.|nuovi|nuovo/nuova/nuovi|Книги новые.', 'Le mele sono ___.|rosse|rosso/rossa/rosse|Яблоки красные.',
     'La bambina è ___.|piccola|piccolo/piccola/piccoli|Девочка маленькая.', 'Il cane è ___.|grande|grande/granda/grandi|Собака большая.', 'Le scarpe sono ___.|nuove|nuovo/nuove/nuova|Туфли новые.', 'Il fratello è ___.|alto|alto/alta/alti|Брат высокий.'],
    ['Il cielo è azzurro.|Небо голубое.', 'La mamma è bella.|Мама красивая.', 'I gatti sono neri.|Коты чёрные.']),
  LG(553, '❤️', 'Mi piace, mi piacciono', 'Как сказать, что нравится? Всё зависит от числа!',
    'Mi piace / mi piacciono', '<ul><li><b>mi piace</b> + один предмет или глагол: <i>Mi piace la pizza. Mi piace correre.</i></li><li><b>mi piacciono</b> + несколько: <i>Mi piacciono i gatti.</i></li><li><b>non mi piace</b> — не нравится</li></ul>',
    ['Mi piace la pizza.|Мне нравится пицца.', 'Mi piacciono i gatti.|Мне нравятся кошки.', 'Non mi piace il latte.|Мне не нравится молоко.'],
    ['Mi ___ la pizza.|piace|piace/piacciono/piaci|Мне нравится пицца.', 'Mi ___ i gatti.|piacciono|piace/piacciono/piaci|Мне нравятся кошки.', 'Non mi ___ il latte.|piace|piace/piacciono/piaci|Мне не нравится молоко.', 'Ti ___ il gelato?|piace|piace/piacciono/piaci|Тебе нравится мороженое?',
     'Ti ___ le mele?|piacciono|piace/piacciono/piaci|Тебе нравятся яблоки?', 'Mi piace ___ la musica.|ascoltare|ascoltare/ascolto/ascolta|Мне нравится слушать музыку.', 'Non mi ___ i ragni.|piacciono|piace/piacciono/piaci|Мне не нравятся пауки.', 'A Marco ___ il calcio.|piace|piace/piacciono/piaci|Марко нравится футбол.'],
    ['Mi piace giocare.|Мне нравится играть.', 'Non mi piacciono i ragni.|Мне не нравятся пауки.', 'Ti piace la pasta?|Тебе нравится паста?']),
  LG(554, '📍', 'C’è e ci sono', 'Как сказать, что где-то что-то есть? Для одного предмета — c’è, для многих — ci sono.',
    'C’è / ci sono', '<ul><li><b>c’è</b> + один предмет: <i>C’è un gatto.</i></li><li><b>ci sono</b> + несколько: <i>Ci sono due gatti.</i></li></ul>',
    ['C’è un gatto.|Есть кот.', 'Ci sono due cani.|Есть две собаки.', 'Nel parco ci sono molti alberi.|В парке много деревьев.'],
    ['Nella stanza ___ un letto.|c’è|c’è/ci sono|В комнате есть кровать.', 'Nel parco ___ molti alberi.|ci sono|c’è/ci sono|В парке много деревьев.', 'Sul tavolo ___ una mela.|c’è|c’è/ci sono|На столе яблоко.', 'In classe ___ venti bambini.|ci sono|c’è/ci sono|В классе двадцать детей.',
     'Nel frigo ___ il latte.|c’è|c’è/ci sono|В холодильнике молоко.', 'Nel cielo ___ tre nuvole.|ci sono|c’è/ci sono|В небе три облака.', 'Qui ___ un gatto.|c’è|c’è/ci sono|Здесь кот.', 'Nel giardino ___ due cani.|ci sono|c’è/ci sono|В саду две собаки.'],
    ['In città c’è un parco.|В городе есть парк.', 'Nello zaino ci sono tre libri.|В рюкзаке три книги.', 'Qui non c’è nessuno.|Здесь никого нет.']),
  LG(555, '📦', 'Sopra, sotto, dentro', 'Где находится предмет? Слова-подсказки помогут описать.',
    'Где находится?', '<ul><li><b>sopra</b> — над, на</li><li><b>sotto</b> — под</li><li><b>dentro</b> — внутри</li><li><b>fuori</b> — снаружи</li><li><b>vicino</b> — рядом</li><li><b>lontano</b> — далеко</li></ul>',
    ['Il gatto è sotto il tavolo.|Кот под столом.', 'La palla è dentro la scatola.|Мяч внутри коробки.', 'La scuola è vicina al parco.|Школа рядом с парком.'],
    ['Il gatto è ___ il tavolo.|sotto|sotto/sopra/fuori|Кот под столом.', 'La lampada è ___ il tavolo.|sopra|sotto/sopra/dentro|Лампа над столом.', 'La palla è ___ la scatola.|dentro|dentro/fuori/lontano|Мяч внутри коробки.', 'Il libro è ___ lo zaino.|dentro|dentro/fuori/lontano|Книга в рюкзаке.',
     'La scuola è ___ al parco.|vicina|vicina/lontana/dentro|Школа рядом с парком.', 'Roma è ___ da Mosca.|lontana|vicina/lontana/dentro|Рим далеко от Москвы.', 'Gli uccelli volano ___ la casa.|sopra|sopra/sotto/dentro|Птицы летают над домом.', 'Il cane è ___ della casa.|fuori|fuori/dentro/sotto|Собака снаружи дома.'],
    ['Il gatto è sotto la sedia.|Кот под стулом.', 'L’uccello è sopra l’albero.|Птица над деревом.', 'Siamo dentro la casa.|Мы внутри дома.']),
  LG(556, '❓', 'Chi? Dove? Quando?', 'Вопросительные слова нужны, чтобы узнать всё на свете.',
    'Вопросительные слова', '<ul><li><b>chi?</b> — кто?</li><li><b>che cosa?</b> — что?</li><li><b>dove?</b> — где?</li><li><b>quando?</b> — когда?</li><li><b>come?</b> — как?</li><li><b>quanto/quanti?</b> — сколько?</li></ul>',
    ['Dove abiti?|Где ты живёшь?', 'Quando è il tuo compleanno?|Когда твой день рождения?', 'Chi è lui?|Кто он?'],
    ['___ ti chiami?|Come|Come/Dove/Chi|Как тебя зовут?', '___ abiti?|Dove|Come/Dove/Chi|Где ты живёшь?', '___ è lui?|Chi|Chi/Dove/Quando|Кто он?', '___ anni hai?|Quanti|Quanti/Quando/Come|Сколько тебе лет?',
     '___ è il tuo compleanno?|Quando|Quando/Dove/Chi|Когда твой день рождения?', '___ stai?|Come|Come/Dove/Quanti|Как ты?', '___ costa la pizza?|Quanto|Quanto/Quanti/Come|Сколько стоит пицца?', '___ la mia penna?|Dov’è|Dov’è/Chi è/Quando è|Где моя ручка?'],
    ['Come stai?|Как ты?', 'Quanti anni hai?|Сколько тебе лет?', 'Dove vai?|Куда ты идёшь?']),
  LG(557, '👤', 'Il mio, la mia', 'Моё, твоё, его — слова-владельцы меняются по роду и числу.',
    'Притяжательные слова', '<ul><li><b>il mio</b> / <b>la mia</b> — мой / моя</li><li><b>i miei</b> / <b>le mie</b> — мои</li><li><b>il tuo</b> / <b>la tua</b> — твой / твоя</li><li><b>il suo</b> / <b>la sua</b> — его, её</li></ul>',
    ['il mio libro|моя книга', 'la mia mamma|моя мама', 'i miei amici|мои друзья'],
    ['Questo è il ___ libro.|mio|mio/mia/miei|Это моя книга.', 'Questa è la ___ mamma.|mia|mio/mia/miei|Это моя мама.', 'Dov’è il ___ zaino?|tuo|tuo/tua/tuoi|Где твой рюкзак?', 'Dov’è la ___ penna?|tua|tuo/tua/tue|Где твоя ручка?',
     'Il ___ gatto è nero.|suo|suo/sua/sui|Его кот чёрный.', 'La ___ casa è grande.|sua|suo/sua/suoi|Его дом большой.', 'Questi sono i ___ amici.|miei|mio/mia/miei|Это мои друзья.', 'Ecco le ___ scarpe.|mie|miei/mie/mia|Вот мои туфли.'],
    ['Questo è il mio gatto.|Это мой кот.', 'La tua casa è bella.|Твой дом красивый.', 'Ecco i miei libri.|Вот мои книги.']),
  LG(558, '🚫', 'Non', 'Чтобы сказать «не», перед глаголом ставят слово non.',
    'Отрицание: non', '<ul><li><i>Io parlo.</i> → <i>Io <b>non</b> parlo.</i></li><li><i>Ho un cane.</i> → <i><b>Non</b> ho un cane.</i></li><li>Короткий ответ: <i>No, non ho fame.</i></li></ul>',
    ['Non parlo inglese.|Я не говорю по-английски.', 'Non ho fame.|Я не голоден.', 'Non piove oggi.|Сегодня нет дождя.'],
    ['Io ___ parlo inglese.|non|non/no/mai|Я не говорю по-английски.', 'No, ___ ho un cane.|non|non/no/mai|Нет, у меня нет собаки.', 'Lei ___ è a casa.|non|non/no/mai|Её нет дома.', 'Noi ___ mangiamo carne.|non|non/no/mai|Мы не едим мясо.',
     'Ti piace il caffè? — No, ___ mi piace.|non|non/no/mai|Нравится кофе? — Нет, не нравится.', 'Oggi ___ piove.|non|non/no/mai|Сегодня нет дождя.', 'Loro ___ sono in classe.|non|non/no/mai|Их нет в классе.', 'Tu ___ hai fame?|non|non/no/mai|Ты не голоден?'],
    ['Non sono stanco.|Я не устал.', 'Non mi piace il caffè.|Мне не нравится кофе.', 'Marco non è a casa.|Марко нет дома.']),
  LR(559, '🦁', 'Il leone e il topo', 'Старая басня. Может ли маленькая мышка помочь большому льву?',
    ['Un leone dorme nella foresta.|Лев спит в лесу.', 'Un piccolo topo corre sul leone.|Маленькая мышь бежит по льву.', 'Il leone si sveglia ed è arrabbiato.|Лев просыпается и сердится.', '«Lasciami andare!» dice il topo.|«Отпусти меня!» говорит мышь.',
     '«Un giorno ti aiuterò.»|«Однажды я тебе помогу.»', 'Il leone ride e lascia andare il topo.|Лев смеётся и отпускает мышь.', 'Un giorno il leone cade in una rete.|Однажды лев попадает в сеть.', 'Il topo rosicchia la rete e il leone è libero.|Мышь перегрызает сеть, и лев свободен.'],
    ['Dove dorme il leone?|Где спит лев?|Nella foresta|Nel mare|In casa', 'Chi corre sul leone?|Кто бежит по льву?|Un topo|Un gatto|Un cane', 'In cosa cade il leone?|Во что попадает лев?|In una rete|In un fiume|In una casa', 'Chi aiuta il leone?|Кто помогает льву?|Il topo|L’uccello|Il cane'],
    [0, 2, 6, 7], ['Il leone dorme.|Лев спит.', 'Il topo aiuta il leone.|Мышь помогает льву.', 'Il leone è libero.|Лев свободен.']),
  LR(560, '🥕', 'La rapa gigante', 'Старая сказка о том, как все вместе вытаскивали огромную репку.',
    ['Il nonno ha una rapa grande.|У дедушки большая репка.', 'Il nonno tira, ma non può.|Дедушка тянет, но не может.', 'La nonna aiuta il nonno.|Бабушка помогает дедушке.', 'La nipotina aiuta la nonna.|Внучка помогает бабушке.',
     'Il cane aiuta la nipotina.|Собака помогает внучке.', 'Il gatto aiuta il cane.|Кот помогает собаке.', 'Il topo aiuta il gatto.|Мышка помогает коту.', 'Tira, tira, tira… la rapa è fuori!|Тяни-потяни… репка вытащена!'],
    ['Chi ha una rapa grande?|У кого большая репка?|Il nonno|Il cane|Il gatto', 'Chi aiuta il gatto?|Кто помогает коту?|Il topo|La nonna|Il nonno', 'Chi aiuta per prima?|Кто помогает первой?|La nonna|Il cane|Il topo', 'Alla fine la rapa è fuori?|В конце репка вытащена?|Sì, è fuori|No, non è fuori|Non si sa'],
    [0, 2, 6, 7], ['Il nonno ha una rapa.|У дедушки есть репка.', 'Il cane aiuta.|Собака помогает.', 'La rapa è fuori!|Репка вытащена!']),
  LW(561, '🔁', 'Ripasso 2', 'Перед вторым боссом вспомним слова из второго мира.',
    ['parco', 'pasta', 'gelato', 'leone', 'autobus', 'primavera', 'calcio', 'cucina', 'mucca', 'medico'],
    ['Vado al parco con il cane.|Я иду в парк с собакой.', 'Mi piace il gelato.|Мне нравится мороженое.', 'In primavera nascono i fiori.|Весной появляются цветы.'])
];
const IT_BOSS2 = { id: 591, title: 'Fortezza della Confusione', icon: '🏯', bossIcon: '🧟' };
