/* Итальянский: Мир 3 «Viaggio in Italia» (уроки 601–630). */
const IT_L3 = [
  LW(601, '🇮🇹', 'Le città italiane', 'Начинаем путешествие по Италии! Найди города на карте.',
    ['Italia|Италия|🇮🇹', 'Roma|Рим|🏺', 'Milano|Милан|🏙️', 'Venezia|Венеция|🚤', 'Napoli|Неаполь|🌋', 'Firenze|Флоренция|🎨', 'Torino|Турин|🏔️', 'Palermo|Палермо|🌴'],
    ['Roma è la capitale d’Italia.|Рим — столица Италии.', 'Venezia è sull’acqua.|Венеция стоит на воде.', 'Firenze è una città d’arte.|Флоренция — город искусства.']),
  LW(602, '🏟️', 'I monumenti', 'Италия полна знаменитых мест. Узнаешь их?',
    ['Colosseo|Колизей|🏟️', 'Torre di Pisa|Пизанская башня|🗼', 'gondola|гондола|🛶', 'Vesuvio|Везувий|🌋', 'fontana|фонтан|⛲', 'ponte|мост|🌉', 'duomo|собор|⛪'],
    ['Il Colosseo è a Roma.|Колизей в Риме.', 'La Torre di Pisa è storta.|Пизанская башня кривая.', 'La gondola va sul canale.|Гондола плывёт по каналу.']),
  LW(603, '🏖️', 'La natura', 'В Италии есть море, горы, озёра и даже вулканы.',
    ['mare|море|🌊', 'montagna|гора|⛰️', 'lago|озеро|🏞️', 'vulcano|вулкан|🌋', 'fiume|река|🛶', 'spiaggia|пляж|🏖️', 'collina|холм|🌄'],
    ['Il mare è azzurro.|Море голубое.', 'In estate vado in spiaggia.|Летом я иду на пляж.', 'Il vulcano è alto.|Вулкан высокий.']),
  LW(604, '🍝', 'La cucina italiana', 'Самая вкусная часть путешествия — итальянская еда!',
    ['spaghetti|спагетти|🍝', 'lasagne|лазанья|🥘', 'risotto|ризотто|🍚', 'tiramisù|тирамису|🍰', 'panino|бутерброд|🥪', 'caffè|кофе|☕', 'olio|масло|🫒'],
    ['Mangio gli spaghetti.|Я ем спагетти.', 'Il tiramisù è dolce.|Тирамису сладкое.', 'La lasagna è calda.|Лазанья горячая.']),
  LW(605, '🍽️', 'Al ristorante', 'Столик заказан! Давай попробуем заказать обед.',
    ['menù|меню|📋', 'cameriere|официант|🤵', 'conto|счёт|🧾', 'forchetta|вилка|🍴', 'coltello|нож|🔪', 'cucchiaio|ложка|🥄', 'piatto|тарелка|🍽️', 'bicchiere|стакан|🥤'],
    ['Il menù, per favore.|Меню, пожалуйста.', 'Il conto, per favore.|Счёт, пожалуйста.', 'Vorrei un bicchiere d’acqua.|Я хотел бы стакан воды.']),
  LW(606, '🛍️', 'Nel negozio', 'Время покупок! Узнай, сколько что стоит.',
    ['negozio', 'prezzo|цена|🏷️', 'euro|евро|💶', 'soldi|деньги|💰', 'carrello|тележка|🛒', 'sacchetto|пакет|🛍️', 'borsa|сумка|👜', 'mercato|рынок|🧺'],
    ['Quanto costa?|Сколько это стоит?', 'Costa cinque euro.|Это стоит пять евро.', 'Vado al mercato.|Я иду на рынок.']),
  LW(607, '🧳', 'In viaggio', 'Чемодан собран! Что нужно для путешествия?',
    ['biglietto|билет|🎫', 'valigia|чемодан|🧳', 'passaporto|паспорт|🛂', 'aeroporto|аэропорт|🛫', 'albergo|гостиница|🏨', 'mappa|карта|🗺️', 'turista|турист|📸'],
    ['Ho un biglietto.|У меня есть билет.', 'La valigia è pesante.|Чемодан тяжёлый.', 'L’albergo è vicino al mare.|Гостиница рядом с морем.']),
  LW(608, '🎄', 'Le feste', 'В Италии много весёлых праздников. Какие знаешь?',
    ['Natale|Рождество|🎄', 'Pasqua|Пасха|🐣', 'Carnevale|Карнавал|🎠', 'maschera|маска|🎭', 'Befana|Бефана|🧙‍♀️', 'fuochi d’artificio|фейерверк|🎆', 'coriandoli|конфетти|🎊'],
    ['A Natale ricevo regali.|На Рождество я получаю подарки.', 'A Carnevale metto una maschera.|На Карнавал я надеваю маску.', 'La Befana porta i dolci.|Бефана приносит сладости.']),
  LW(609, '🎶', 'La musica', 'Италия — родина оперы. Научимся называть инструменты.',
    ['chitarra|гитара|🎸', 'pianoforte|пианино|🎹', 'tamburo|барабан|🥁', 'violino|скрипка|🎻', 'canzone|песня|🎶', 'cantante|певец|🎤', 'opera|опера|🎭'],
    ['Suono la chitarra.|Я играю на гитаре.', 'Mi piace questa canzone.|Мне нравится эта песня.', 'Il cantante canta bene.|Певец хорошо поёт.']),
  LW(610, '🧣', 'Vestiti (2)', 'Что взять с собой в дорогу? Всё зависит от сезона!',
    ['maglione|свитер|🧶', 'sciarpa|шарф|🧣', 'guanti|перчатки|🧤', 'stivali|сапоги|🥾', 'costume|купальник|🩱', 'occhiali da sole|солнечные очки|🕶️', 'pantaloncini|шорты|🩳'],
    ['In inverno metto la sciarpa.|Зимой я надеваю шарф.', 'In estate porto gli occhiali da sole.|Летом я ношу солнечные очки.', 'Ho un maglione caldo.|У меня тёплый свитер.']),
  LW(611, '🥇', 'Primo, secondo, terzo', 'Порядковые числительные нужны, когда считаем места и этажи.',
    ['primo|первый|1', 'secondo|второй|2', 'terzo|третий|3', 'quarto|четвёртый|4', 'quinto|пятый|5', 'sesto|шестой|6', 'settimo|седьмой|7', 'ottavo|восьмой|8', 'nono|девятый|9', 'decimo|десятый|10'],
    ['Sono il primo.|Я первый.', 'Abito al terzo piano.|Я живу на третьем этаже.', 'Il decimo giorno è domenica.|Десятый день — воскресенье.']),
  LG(612, '📖', 'Leggere, dormire', 'Кроме -are, есть глаголы на -ere и -ire. У них свои окончания.',
    'Глаголы на -ere и -ire', '<ul><li><b>leggere</b>: io legg<b>o</b>, tu legg<b>i</b>, lui legg<b>e</b>, noi legg<b>iamo</b>, voi legg<b>ete</b>, loro legg<b>ono</b></li><li><b>dormire</b>: io dorm<b>o</b>, tu dorm<b>i</b>, lui dorm<b>e</b>, noi dorm<b>iamo</b>, voi dorm<b>ite</b>, loro dorm<b>ono</b></li></ul>',
    ['Io leggo un libro.|Я читаю книгу.', 'Tu dormi molto.|Ты много спишь.', 'Noi scriviamo una lettera.|Мы пишем письмо.'],
    ['Io ___ un libro.|leggo|leggo/leggi/legge|Я читаю книгу.', 'Tu ___ molto.|dormi|dormo/dormi/dorme|Ты много спишь.', 'Marco ___ una lettera.|scrive|scrivo/scrivi/scrive|Марко пишет письмо.', 'Noi ___ la pizza.|prendiamo|prendiamo/prendete/prendono|Мы берём пиццу.',
     'Voi ___ sul divano.|dormite|dormiamo/dormite/dormono|Вы спите на диване.', 'Loro ___ il giornale.|leggono|leggiamo/leggete/leggono|Они читают газету.', 'Lei ___ la porta.|apre|apro/apri/apre|Она открывает дверь.', 'Io ___ la finestra.|chiudo|chiudo/chiudi/chiude|Я закрываю окно.'],
    ['Leggo un libro interessante.|Я читаю интересную книгу.', 'Il bambino dorme.|Ребёнок спит.', 'Voi scrivete bene.|Вы хорошо пишете.']),
  LG(613, '✨', 'Volere e potere', 'Два важных глагола: хотеть и мочь. После них стоит глагол в начальной форме.',
    'volere и potere', '<ul><li><b>volere</b>: io voglio, tu vuoi, lui vuole, noi vogliamo, voi volete, loro vogliono</li><li><b>potere</b>: io posso, tu puoi, lui può, noi possiamo, voi potete, loro possono</li></ul><p>Voglio mangiare. Posso giocare?</p>',
    ['Voglio un gelato.|Я хочу мороженое.', 'Posso entrare?|Можно войти?', 'Vuoi giocare?|Хочешь поиграть?'],
    ['Io ___ un gelato.|voglio|voglio/vuoi/vuole|Я хочу мороженое.', 'Tu ___ giocare?|vuoi|voglio/vuoi/vuole|Ты хочешь играть?', 'Lei ___ un panino.|vuole|voglio/vuoi/vuole|Она хочет бутерброд.', 'Noi ___ andare al mare.|vogliamo|vogliamo/volete/vogliono|Мы хотим пойти на море.',
     'Tu ___ nuotare?|puoi|posso/puoi/può|Ты можешь плавать?', 'Lui ___ correre veloce.|può|posso/puoi/può|Он может быстро бегать.', 'Loro ___ giocare qui.|possono|possiamo/potete/possono|Они могут играть здесь.', 'Io ___ aiutare.|posso|posso/puoi/può|Я могу помочь.'],
    ['Voglio mangiare.|Я хочу есть.', 'Non posso venire.|Я не могу прийти.', 'Possiamo giocare?|Можно нам поиграть?']),
  LG(614, '🚶', 'Andare', 'Куда ты идёшь? Нужен глагол andare и предлоги a, in.',
    'andare — «идти, ехать»', '<ul><li>io <b>vado</b>, tu <b>vai</b>, lui <b>va</b>, noi <b>andiamo</b>, voi <b>andate</b>, loro <b>vanno</b></li><li><b>a</b> + город: <i>a Roma</i></li><li><b>in</b> + страна: <i>in Italia</i></li></ul>',
    ['Vado a scuola.|Я иду в школу.', 'Vai in Italia.|Ты едешь в Италию.', 'Andiamo al mare.|Мы идём на море.'],
    ['Io ___ a scuola.|vado|vado/vai/va|Я иду в школу.', 'Tu ___ al parco.|vai|vado/vai/va|Ты идёшь в парк.', 'Lei ___ in Italia.|va|vado/vai/va|Она едет в Италию.', 'Noi ___ al mare.|andiamo|andiamo/andate/vanno|Мы едем на море.',
     'Voi ___ a casa.|andate|andiamo/andate/vanno|Вы идёте домой.', 'Loro ___ a Roma.|vanno|andiamo/andate/vanno|Они едут в Рим.', 'Vado ___ Roma.|a|a/in/da|Я еду в Рим.', 'Vado ___ Italia.|in|a/in/da|Я еду в Италию.'],
    ['Vado a Milano.|Я еду в Милан.', 'Andiamo in Francia.|Мы едем во Францию.', 'Dove vai?|Куда ты идёшь?']),
  LG(615, '🛠️', 'Fare', 'Глагол fare — «делать». Он есть и в вопросе про погоду!',
    'fare — «делать»', '<ul><li>io <b>faccio</b>, tu <b>fai</b>, lui <b>fa</b>, noi <b>facciamo</b>, voi <b>fate</b>, loro <b>fanno</b></li><li><b>Che tempo fa?</b> — Какая погода? <b>Fa caldo.</b> — Жарко.</li></ul>',
    ['Faccio colazione.|Я завтракаю.', 'Che tempo fa?|Какая погода?', 'Oggi fa freddo.|Сегодня холодно.'],
    ['Io ___ colazione.|faccio|faccio/fai/fa|Я завтракаю.', 'Tu ___ i compiti.|fai|faccio/fai/fa|Ты делаешь уроки.', 'Lei ___ una torta.|fa|faccio/fai/fa|Она печёт торт.', 'Noi ___ una passeggiata.|facciamo|facciamo/fate/fanno|Мы гуляем.',
     'Che tempo ___?|fa|fa/fai/fanno|Какая погода?', 'Oggi ___ freddo.|fa|fa/è/ha|Сегодня холодно.', 'Loro ___ un gioco.|fanno|facciamo/fate/fanno|Они играют в игру.', 'Voi ___ la spesa.|fate|facciamo/fate/fanno|Вы делаете покупки.'],
    ['Faccio i compiti.|Я делаю уроки.', 'Fa caldo in estate.|Летом жарко.', 'Facciamo una torta.|Мы печём торт.']),
  LG(616, '🧭', 'A, in, di, da', 'Маленькие слова-предлоги помогают сказать куда, откуда и чьё.',
    'Предлоги a, in, di, da', '<ul><li><b>a</b> — в, к (города): <i>vado a Roma</i></li><li><b>in</b> — в (страны): <i>sono in Italia</i></li><li><b>di</b> — из, чей: <i>sono di Milano</i>, <i>il libro di Marco</i></li><li><b>da</b> — от, у: <i>vengo da Roma</i>, <i>vado da Marco</i></li></ul>',
    ['Sono di Roma.|Я из Рима.', 'Vengo da Milano.|Я приезжаю из Милана.', 'Il libro di Marco.|Книга Марко.'],
    ['Vado ___ scuola.|a|a/di/da|Я иду в школу.', 'Sono ___ Roma.|di|di/a/in|Я из Рима.', 'Il libro ___ Marco.|di|di/da/in|Книга Марко.', 'Vengo ___ Milano.|da|da/di/a|Я приезжаю из Милана.',
     'Siamo ___ Italia.|in|in/a/da|Мы в Италии.', 'Vado ___ Marco.|da|a/da/di|Я иду к Марко.', 'Il treno ___ Roma.|per|per/da/con|Поезд на Рим.', 'Gioco ___ il mio amico.|con|con/di/su|Я играю с другом.'],
    ['Abito a Torino.|Я живу в Турине.', 'Il gatto di Anna è nero.|Кот Анны чёрный.', 'Vado in vacanza con la mamma.|Я еду в отпуск с мамой.']),
  LG(617, '🕒', 'Che ore sono?', 'Узнаём время по-итальянски. Для этого нужны числа и слова «e mezza» — «половина».',
    'Который час?', '<ul><li><b>È l’una.</b> — Час.</li><li><b>Sono le tre.</b> — Три часа.</li><li><b>…e mezza</b> — половина: <i>Sono le otto e mezza.</i></li><li><b>…e un quarto</b> — пятнадцать минут</li><li><b>…meno un quarto</b> — без пятнадцати</li></ul>',
    ['Che ore sono?|Который час?', 'Sono le otto e mezza.|Половина девятого (8:30).', 'È l’una.|Час дня.'],
    ['Che ore ___?|sono|sono/è/ha|Который час?', '___ le tre.|Sono|Sono/È/Ha|Три часа.', '___ l’una.|È|Sono/È/Ha|Час.', 'Sono le otto e ___.|mezza|mezza/quarto/meno|Восемь тридцать.',
     'Sono le due e un ___.|quarto|quarto/mezza/meno|Два пятнадцать.', 'Sono le cinque ___ un quarto.|meno|meno/e/di|Без пятнадцати пять.', 'A che ora ___ la scuola?|inizia|inizia/inizio/iniziano|Во сколько начинается школа?', 'Il film inizia ___ otto.|alle|alle/le/a|Фильм начинается в восемь.'],
    ['Sono le dieci.|Десять часов.', 'Mangio alle dodici.|Я ем в двенадцать.', 'Che ore sono adesso?|Который сейчас час?']),
  LG(618, '💶', 'Quanto costa?', 'Покупаем мороженое! Спрашиваем цену и отвечаем.',
    'Сколько это стоит?', '<ul><li><b>Quanto costa?</b> — Сколько стоит (один предмет)?</li><li><b>Quanto costano?</b> — Сколько стоят (несколько)?</li><li><b>Costa tre euro.</b> — Стоит три евро.</li><li><b>Vorrei…</b> — Я бы хотел…</li></ul>',
    ['Quanto costa il gelato?|Сколько стоит мороженое?', 'Costa due euro.|Стоит два евро.', 'Vorrei un panino.|Я бы хотел бутерброд.'],
    ['Quanto ___ il gelato?|costa|costa/costano/costo|Сколько стоит мороженое?', 'Quanto ___ le mele?|costano|costa/costano/costo|Сколько стоят яблоки?', 'Costa due ___.|euro|euro/euri/euros|Стоит два евро.', 'Il panino costa ___ euro.|tre|tre/tra/tri|Бутерброд стоит три евро.',
     'Vorrei un ___.|gelato|gelato/gelati/gelata|Я бы хотел мороженое.', 'Ecco ___ euro.|dieci|dieci/dici/decimo|Вот десять евро.', 'Il conto è di ___ euro.|venti|venti/vento/vente|Счёт двадцать евро.', 'Grazie! — ___!|Prego|Prego/Ciao/Scusa|Спасибо! — Пожалуйста!'],
    ['Quanto costa questo?|Сколько это стоит?', 'Costa cinque euro.|Это стоит пять евро.', 'Un gelato, per favore.|Одно мороженое, пожалуйста.']),
  LG(619, '📣', 'Guarda! Ascolta!', 'Команды помогают играть: скажем, что делать другу.',
    'Приказ: guarda, ascolta…', '<ul><li><b>Guarda!</b> — Смотри!</li><li><b>Ascolta!</b> — Слушай!</li><li><b>Mangia!</b> — Ешь!</li><li><b>Scrivi!</b> — Пиши!</li><li><b>Vieni qui!</b> — Иди сюда!</li></ul>',
    ['Guarda!|Смотри!', 'Ascolta la musica!|Слушай музыку!', 'Vieni qui!|Иди сюда!'],
    ['___! Un gatto!|Guarda|Guarda/Guardo/Guardi|Смотри! Кот!', '___ la musica!|Ascolta|Ascolta/Ascolto/Ascolti|Слушай музыку!', '___ la pizza!|Mangia|Mangia/Mangio/Mangi|Ешь пиццу!', '___ il tuo nome!|Scrivi|Scrivi/Scrivo/Scrive|Напиши своё имя!',
     '___ la porta!|Chiudi|Chiudi/Chiudo/Chiude|Закрой дверь!', '___ qui!|Vieni|Vieni/Vengo/Viene|Иди сюда!', '___ il libro!|Leggi|Leggi/Leggo/Legge|Читай книгу!', '___ la finestra!|Apri|Apri/Apro/Apre|Открой окно!'],
    ['Guarda il mare!|Смотри на море!', 'Ascolta bene.|Слушай внимательно.', 'Apri il libro.|Открой книгу.']),
  LG(620, '⏪', 'Ieri ho mangiato', 'Как рассказать, что было вчера? Используем ho + причастие.',
    'Прошедшее время (passato prossimo)', '<ul><li><b>ho / hai / ha / abbiamo / avete / hanno</b> + причастие</li><li>-are → <b>-ato</b>: mangi<b>ato</b>, guard<b>ato</b></li><li>-ere → <b>-uto</b>: bev<b>uto</b></li><li>особые: letto (читал), scritto (писал)</li></ul>',
    ['Ho mangiato la pizza.|Я съел пиццу.', 'Hai guardato il film?|Ты смотрел фильм?', 'Abbiamo giocato.|Мы играли.'],
    ['Ieri ho ___ la pizza.|mangiato|mangiato/mangio/mangiare|Вчера я ел пиццу.', 'Ho ___ la televisione.|guardato|guardato/guardo/guardare|Я смотрел телевизор.', 'Hai ___ il latte?|bevuto|bevuto/bevo/bere|Ты выпил молоко?', 'Abbiamo ___ al parco.|giocato|giocato/giochiamo/giocare|Мы играли в парке.',
     'Marco ha ___ una lettera.|scritto|scritto/scrive/scrivere|Марко написал письмо.', 'Ho ___ un libro.|letto|letto/leggo/leggere|Я прочитал книгу.', 'Ieri ___ andato al mare.|sono|sono/ho/ha|Вчера я ходил на море.', 'Loro hanno ___ la torta.|mangiato|mangiato/mangiano/mangiare|Они съели торт.'],
    ['Ieri ho giocato a calcio.|Вчера я играл в футбол.', 'Ho scritto una lettera.|Я написал письмо.', 'Abbiamo mangiato il gelato.|Мы съели мороженое.']),
  LR(621, '🪵', 'Pinocchio', 'Знаменитая итальянская сказка о деревянном мальчике.',
    ['Geppetto è un falegname.|Джеппетто — плотник.', 'Costruisce un burattino di legno.|Он делает деревянную куклу.', 'Il burattino si chiama Pinocchio.|Куклу зовут Пиноккио.', 'Pinocchio parla e cammina!|Пиноккио говорит и ходит!',
     'Quando dice una bugia, il naso cresce.|Когда он лжёт, нос растёт.', 'Pinocchio dice la verità.|Пиноккио говорит правду.', 'Diventa un bambino vero.|Он становится настоящим мальчиком.'],
    ['Chi è Geppetto?|Кто такой Джеппетто?|Un falegname|Un cuoco|Un medico', 'Di che cosa è fatto Pinocchio?|Из чего сделан Пиноккио?|Di legno|Di ferro|Di carta', 'Che cosa succede quando Pinocchio dice una bugia?|Что происходит, когда Пиноккио лжёт?|Il naso cresce|Il naso sparisce|Le orecchie crescono', 'Alla fine Pinocchio è…|В конце Пиноккио…|un bambino vero|ancora di legno|un gatto'],
    [0, 1, 4, 6], ['Pinocchio è di legno.|Пиноккио деревянный.', 'Il naso cresce.|Нос растёт.', 'Pinocchio dice la verità.|Пиноккио говорит правду.']),
  LR(622, '🐷', 'I tre porcellini', 'Кто построил самый прочный дом?',
    ['Tre porcellini vivono nel bosco.|Три поросёнка живут в лесу.', 'Il primo fa una casa di paglia.|Первый строит дом из соломы.', 'Il secondo fa una casa di legno.|Второй строит дом из дерева.', 'Il terzo fa una casa di mattoni.|Третий строит дом из кирпичей.',
     'Arriva il lupo e soffia sulla casa di paglia.|Приходит волк и дует на соломенный дом.', 'La casa vola via!|Дом разлетается!', 'Il lupo non può rompere la casa di mattoni.|Волк не может разрушить кирпичный дом.', 'I tre porcellini sono salvi.|Все три поросёнка спасены.'],
    ['Quanti porcellini ci sono?|Сколько поросят?|Tre|Due|Quattro', 'Di che cosa è la casa del terzo?|Из чего дом третьего?|Di mattoni|Di paglia|Di legno', 'Chi soffia sulle case?|Кто дует на дома?|Il lupo|Il gatto|Il cane', 'Quale casa è più forte?|Какой дом самый прочный?|Quella di mattoni|Quella di paglia|Quella di legno'],
    [1, 2, 3, 6], ['Il lupo soffia.|Волк дует.', 'La casa di mattoni è forte.|Кирпичный дом прочный.', 'I porcellini sono salvi.|Поросята спасены.']),
  LR(623, '🐱', 'Il gatto con gli stivali', 'Умный кот в сапогах помогает своему хозяину.',
    ['Un mugnaio ha un gatto.|У мельника есть кот.', 'Il gatto ha un paio di stivali.|У кота есть сапоги.', 'Il gatto porta una lepre al re.|Кот приносит королю зайца.', '«Il mio padrone è il marchese!» dice.|«Мой хозяин — маркиз!» — говорит он.',
     'Il re è contento.|Король доволен.', 'Il gatto diventa ricco e famoso.|Кот становится богатым и знаменитым.'],
    ['Che cosa porta il gatto al re?|Что кот приносит королю?|Una lepre|Un pesce|Una torta', 'Che cosa ha il gatto?|Что есть у кота?|Gli stivali|Un cappello|Una borsa', 'Il re è…|Король…|contento|triste|arrabbiato', 'Chi ha un gatto?|У кого есть кот?|Il mugnaio|Il re|Il lupo'],
    [0, 1, 2, 5], ['Il gatto ha gli stivali.|У кота есть сапоги.', 'Il re è contento.|Король доволен.', 'Il gatto è famoso.|Кот знаменит.']),
  LR(624, '🛶', 'Venezia', 'Город на воде, где вместо улиц — каналы.',
    ['Venezia è una città sull’acqua.|Венеция — город на воде.', 'In città non ci sono strade, ci sono canali.|В городе нет улиц, есть каналы.', 'Le persone viaggiano in barca.|Люди ездят на лодках.', 'La gondola è una barca speciale.|Гондола — особая лодка.',
     'Il gondoliere canta una canzone.|Гондольер поёт песню.', 'A Venezia ci sono molti ponti.|В Венеции много мостов.'],
    ['Dov’è Venezia?|Где Венеция?|Sull’acqua|Sulla montagna|Nel deserto', 'Che cosa ci sono al posto delle strade?|Что вместо улиц?|I canali|Le piste|I prati', 'Che cos’è una gondola?|Что такое гондола?|Una barca|Un treno|Una casa', 'Chi canta?|Кто поёт?|Il gondoliere|Il cuoco|Il medico'],
    [0, 1, 3, 4], ['A Venezia ci sono i canali.|В Венеции есть каналы.', 'La gondola è una barca.|Гондола — лодка.', 'Il gondoliere canta.|Гондольер поёт.']),
  LR(625, '🏛️', 'Una giornata a Roma', 'Анна и мама гуляют по Риму.',
    ['Anna è a Roma con la mamma.|Анна в Риме с мамой.', 'La mattina vedono il Colosseo.|Утром они видят Колизей.', 'A pranzo mangiano la pizza.|На обед они едят пиццу.', 'Il pomeriggio visitano una fontana.|После обеда они осматривают фонтан.',
     'Anna lancia una moneta e fa un desiderio.|Анна бросает монетку и загадывает желание.', 'La sera mangiano il gelato.|Вечером они едят мороженое.'],
    ['Con chi è Anna a Roma?|С кем Анна в Риме?|Con la mamma|Con il nonno|Da sola', 'Che cosa vedono la mattina?|Что они видят утром?|Il Colosseo|Il mare|La neve', 'Che cosa mangiano a pranzo?|Что едят на обед?|La pizza|La pasta|Il pesce', 'Che cosa fa Anna alla fontana?|Что делает Анна у фонтана?|Lancia una moneta|Beve acqua|Dorme'],
    [1, 2, 4, 5], ['Anna vede il Colosseo.|Анна видит Колизей.', 'Mangiano la pizza.|Они едят пиццу.', 'La sera mangiano il gelato.|Вечером они едят мороженое.']),
  LR(626, '🧺', 'Cappuccetto Rosso', 'Помнишь сказку про волка и бабушку?',
    ['Cappuccetto Rosso va dalla nonna.|Красная Шапочка идёт к бабушке.', 'Porta una cesta con torta e miele.|Несёт корзинку с пирогом и мёдом.', 'Nel bosco incontra il lupo.|В лесу она встречает волка.', 'Il lupo corre dalla nonna.|Волк бежит к бабушке.',
     'Cappuccetto arriva e dice: «Che occhi grandi hai!»|Шапочка приходит и говорит: «Какие у тебя большие глаза!»', 'Arriva il cacciatore e salva tutti.|Приходит охотник и спасает всех.'],
    ['Dove va Cappuccetto?|Куда идёт Шапочка?|Dalla nonna|A scuola|Al mare', 'Che cosa porta nella cesta?|Что несёт в корзинке?|Una torta|Un libro|Un pesce', 'Chi incontra nel bosco?|Кого встречает в лесу?|Il lupo|L’orso|La volpe', 'Chi salva tutti?|Кто всех спасает?|Il cacciatore|Il nonno|Il gatto'],
    [0, 2, 3, 5], ['Cappuccetto va dalla nonna.|Шапочка идёт к бабушке.', 'Il lupo corre.|Волк бежит.', 'Il cacciatore salva tutti.|Охотник спасает всех.']),
  LR(627, '🦢', 'Il brutto anatroccolo', 'Грустная и красивая сказка о том, как важно не сдаваться.',
    ['Una mamma anatra ha cinque uova.|У мамы-утки пять яиц.', 'Quattro anatroccoli sono gialli.|Четверо утят жёлтые.', 'Uno è grigio e grande.|Один серый и большой.', 'Gli altri dicono: «Sei brutto!»|Остальные говорят: «Ты некрасивый!»',
     'L’anatroccolo è triste e va via.|Утёнок грустит и уходит.', 'In primavera vede il lago: è un bel cigno!|Весной он видит озеро: он красивый лебедь!'],
    ['Quante uova ha la mamma anatra?|Сколько яиц у мамы-утки?|Cinque|Tre|Dieci', 'Di che colore è l’anatroccolo brutto?|Какого цвета «некрасивый» утёнок?|Grigio|Giallo|Rosso', 'Che cosa dicono gli altri?|Что говорят остальные?|«Sei brutto!»|«Sei bravo!»|«Ciao!»', 'Alla fine l’anatroccolo è…|В конце утёнок…|un cigno|un cane|un gatto'],
    [0, 3, 4, 5], ['L’anatroccolo è grigio.|Утёнок серый.', 'È triste.|Ему грустно.', 'Alla fine è un cigno.|В конце он лебедь.']),
  LR(628, '🍪', 'Il biscotto che scappa', 'Старая сказка о печенье, которое убегало от всех.',
    ['Una nonna fa un biscotto grande.|Бабушка печёт большое печенье.', 'Il biscotto salta dalla finestra e scappa.|Печенье выпрыгивает в окно и убегает.', 'Incontra un coniglio: «Ti mangio!»|Встречает кролика: «Съем тебя!»', '«Sono scappato dalla nonna e scappo da te!»|«Я убежал от бабушки и от тебя убегу!»',
     'Poi incontra un lupo e un orso.|Потом встречает волка и медведя.', 'Alla fine incontra una volpe furba.|В конце встречает хитрую лису.', 'La volpe mangia il biscotto.|Лиса съедает печенье.'],
    ['Chi fa il biscotto?|Кто печёт печенье?|La nonna|Il nonno|La volpe', 'Da dove scappa il biscotto?|Откуда убегает печенье?|Dalla finestra|Dalla porta|Dal tetto', 'Chi incontra per primo?|Кого встречает первым?|Un coniglio|Un lupo|Un orso', 'Chi mangia il biscotto?|Кто съедает печенье?|La volpe|Il lupo|L’orso'],
    [0, 1, 2, 6], ['La nonna fa un biscotto.|Бабушка печёт печенье.', 'Il biscotto scappa.|Печенье убегает.', 'La volpe è furba.|Лиса хитрая.']),
  LR(631, '🍇', 'La volpe e l’uva', 'Старая басня о хитрой лисе и высоком винограде.',
    ['Una volpe ha molta fame.|У лисы сильный голод.', 'Vede dell’uva in alto, su un albero.|Она видит виноград высоко на дереве.', 'La volpe salta, ma non arriva all’uva.|Лиса прыгает, но не достаёт до винограда.', 'Prova ancora e ancora.|Она пробует снова и снова.',
     'Alla fine dice: «Questa uva è acerba!»|В конце говорит: «Этот виноград зелёный!»', 'E se ne va.|И уходит.'],
    ['Che cosa vede la volpe?|Что видит лиса?|L’uva|Il pane|Un coniglio', 'Dov’è l’uva?|Где виноград?|Su un albero|In un cesto|A terra', 'La volpe arriva all’uva?|Лиса достаёт до винограда?|No, non arriva|Sì, arriva|Non salta', 'Che cosa dice alla fine?|Что говорит в конце?|«Questa uva è acerba!»|«Che buona!»|«Ciao, uva!»'],
    [0, 1, 2, 4], ['La volpe ha fame.|У лисы голод.', 'L’uva è in alto.|Виноград высоко.', 'La volpe salta.|Лиса прыгает.']),
  LW(629, '🔁', 'Ripasso del viaggio', 'Вспомним слова из путешествия по Италии!',
    ['Roma', 'mare', 'pizza', 'biglietto', 'valigia', 'gelato', 'euro', 'mappa', 'piazza', 'treno'],
    ['Vado a Roma in treno.|Я еду в Рим на поезде.', 'Ho un biglietto per Venezia.|У меня есть билет в Венецию.', 'Mangio un gelato in piazza.|Я ем мороженое на площади.']),
  LG(630, '🧠', 'Ripasso grammatica', 'Последняя проверка перед боссом: глаголы, артикли, множественное число.',
    'Повторение', '<ul><li><b>essere</b>: io sono, tu sei, lui è</li><li><b>avere</b>: io ho, tu hai, lui ha</li><li><b>артикли</b>: il, lo, la, l’</li><li><b>множественное</b>: -o→-i, -a→-e</li><li><b>прошедшее</b>: ho + -ato</li></ul>',
    ['Io sono italiano.|Я итальянец.', 'Lei ha fame.|Она голодна.', 'Ho mangiato la pasta.|Я съел пасту.'],
    ['Io ___ italiano.|sono|sono/sei/è|Я итальянец.', 'Lei ___ fame.|ha|ho/ha/hai|Она голодна.', '___ gatto è nero.|Il|Il/Lo/La|Кот чёрный.', 'Ho due cas___.|e|i/e/o|У меня два дома.',
     'Noi ___ al mare.|andiamo|andiamo/andate/vanno|Мы идём на море.', 'Mi ___ i gelati.|piacciono|piace/piacciono/piaci|Мне нравится мороженое.', 'Quanto ___ la pizza?|costa|costa/costano/costo|Сколько стоит пицца?', 'Ieri ho ___ la pasta.|mangiato|mangiato/mangio/mangiare|Вчера я ел пасту.'],
    ['Il mio gatto è nero.|Мой кот чёрный.', 'Vado a scuola ogni giorno.|Я хожу в школу каждый день.', 'Mi piacciono i gelati.|Мне нравится мороженое.'])
];
const IT_BOSS3 = { id: 592, title: 'Cittadella dell’Oblio', icon: '🏰', bossIcon: '🧙' };
const IT_WORLDS = [
  { name: 'Мир 1 · Primi passi', lessons: IT_L1, boss: IT_BOSS1 },
  { name: 'Мир 2 · La mia vita', lessons: IT_L2, boss: IT_BOSS2 },
  { name: 'Мир 3 · Viaggio in Italia', lessons: IT_L3, boss: IT_BOSS3 }
];
