/* Итальянский: диалоги и песенки-рифмовки. Диалог открывается после урока req, песенка тоже. */
// реплика: «итальянский|перевод|верный ответ|вариант|вариант»
const DI = (id, world, req, icon, title, npc, e, turns) => ({ id, world, req, icon, title, npc: { name: npc, e }, turns: turns.map(t => { const [en, ru, ans, o2, o3] = t.split('|'); return { en, ru, ans, opts: [ans, o2, o3] }; }) });
// строка песенки: «текст|перевод|слово в конце|вариант|вариант» (слово-пропуск — последнее слово строки)
const SO = (id, world, req, icon, title, lines) => ({ id, world, req, icon, title, lines: lines.map(l => { const [en, ru, gap, o2, o3] = l.split('|'); return { en, ru, gap, opts: [gap, o2, o3] }; }) });

const IT_DIALOGS = [
  DI('id1', 0, 501, '👋', 'Знакомство', 'Paolo', '🧑‍🌾', ['Ciao!|Привет!|Ciao!|Arrivederci!|No.', 'Come ti chiami?|Как тебя зовут?|Mi chiamo Bolt.|Ho nove anni.|Sì, grazie.', 'Come stai?|Как дела?|Sto bene, grazie.|Mi chiamo Bolt.|Arrivederci.', 'Arrivederci!|До свидания!|Arrivederci!|Buongiorno!|Sì, grazie.']),
  DI('id2', 0, 509, '👨‍👩‍👧', 'Моя семья', 'Sofia', '👧', ['Chi è lui?|Кто он?|È mio fratello.|È il mio gatto.|Sono io.', 'Hai una sorella?|У тебя есть сестра?|Sì, ho una sorella.|No, ho un gatto.|Mi chiamo Anna.', 'Quanti anni ha?|Сколько ей лет?|Ha sette anni.|Ho sette anni.|Sono sette.', 'Che bella famiglia!|Какая красивая семья!|Grazie!|Prego!|Scusa!']),
  DI('id3', 0, 510, '🧸', 'Магазин игрушек', 'Venditore', '🧑‍💼', ['Buongiorno! Posso aiutarti?|Добрый день! Могу помочь?|Sì, vorrei un robot.|Sì, sono un robot.|No, arrivederci.', 'Di che colore?|Какого цвета?|Blu, per favore.|È un robot.|Ho sei anni.', 'Ecco a te.|Вот, держи.|Grazie!|Scusa!|Ciao, mamma.', 'Arrivederci!|До свидания!|Arrivederci!|Buonanotte!|Sì, grazie.']),
  DI('id4', 0, 518, '☀️', 'Какая погода?', 'Amico', '🧒', ['Ciao! Che tempo fa?|Привет! Какая погода?|C’è il sole.|È lunedì.|Sono felice.', 'Fa caldo?|Жарко?|Sì, fa caldo.|Sì, sono io.|No, grazie.', 'Andiamo a giocare fuori?|Пойдём играть на улицу?|Sì, andiamo!|No, non sono.|Mi chiamo Luca.', 'Corriamo!|Побежали!|Via!|Scusa.|Prego.']),
  DI('id5', 0, 524, '🎒', 'В школе', 'Compagno', '🧑‍🎓', ['Hai una penna?|У тебя есть ручка?|Sì, ecco la penna.|No, ho fame.|Sì, mi chiamo Anna.', 'Che materia hai oggi?|Какой сегодня предмет?|Ho matematica.|Ho dieci anni.|Ho una penna.', 'Ti piace la matematica?|Тебе нравится математика?|Sì, mi piace molto.|Sì, ho una matita.|No, sono otto.', 'A domani!|До завтра!|A domani!|Buonanotte, grazie.|Come stai?']),
  DI('id6', 0, 513, '🥖', 'В пекарне', 'Panettiere', '🧑‍🍳', ['Buongiorno! Cosa desideri?|Добрый день! Что желаешь?|Un pane, per favore.|Mi chiamo pane.|Sono un panino.', 'Altro?|Что-нибудь ещё?|Un succo, per favore.|Sì, sono io.|No, ho sette anni.', 'Sono due euro.|С вас два евро.|Ecco i soldi.|Ecco la luna.|Sono felice.', 'Grazie, arrivederci!|Спасибо, до свидания!|Arrivederci!|Buonanotte!|No, grazie.']),
  DI('id7', 0, 516, '🎂', 'День рождения', 'Giulia', '👧', ['Buon compleanno!|С днём рождения!|Grazie!|Prego!|Scusa!', 'Quanti anni hai?|Сколько тебе лет?|Ho otto anni.|Mi chiamo Giulia.|Sto bene.', 'Ecco un regalo per te.|Вот подарок для тебя.|Grazie mille!|Prego!|Arrivederci!', 'Vuoi la torta?|Хочешь торт?|Sì, grazie!|Sì, sono io.|No, buonanotte.']),
  DI('id8', 0, 519, '🏃', 'Что любишь делать?', 'Marco', '🧒', ['Cosa ti piace fare?|Что ты любишь делать?|Mi piace giocare a calcio.|Mi piace il rosso.|Ho dieci anni.', 'Sai nuotare?|Ты умеешь плавать?|Sì, so nuotare.|Sì, sono blu.|No, grazie.', 'Giochiamo insieme?|Поиграем вместе?|Sì, volentieri!|No, sono due.|Prego.', 'Che bello!|Как здорово!|Sì, è bello!|Sì, mi chiamo Max.|No, non ho.']),
  DI('id9', 1, 532, '🏙️', 'Как пройти?', 'Passante', '🧑', ['Scusa, dov’è la stazione?|Извините, где вокзал?|È vicino al parco.|Mi chiamo Luca.|Sono le tre.', 'È lontana?|Это далеко?|No, è vicina.|Sì, è rossa.|No, ho fame.', 'Grazie mille!|Большое спасибо!|Prego!|Scusa!|Arrivederci, mamma.', 'Buona giornata!|Хорошего дня!|Anche a te!|Sì, grazie.|Sto male.']),
  DI('id10', 1, 537, '🍕', 'В пиццерии', 'Cameriere', '🤵', ['Buonasera! Cosa prendi?|Добрый вечер! Что будешь?|Una pizza, per favore.|Un grande sole.|Sono felice.', 'E da bere?|А пить?|Acqua, grazie.|Pizza, grazie.|Sì, è rosso.', 'Ecco la pizza.|Вот пицца.|Grazie, buon appetito!|Grazie, buonanotte!|No, grazie, ho sonno.', 'Vuoi altro?|Хочешь ещё что-нибудь?|No, il conto, per favore.|No, il gatto, per favore.|Sì, ho sei anni.']),
  DI('id11', 1, 540, '🐄', 'На ферме', 'Contadino', '🧑‍🌾', ['Cosa fa la mucca?|Что делает корова?|Dà il latte.|Dà il pane.|Vola.', 'E la gallina?|А курица?|Fa le uova.|Fa il latte.|Nuota.', 'Ti piacciono gli animali?|Тебе нравятся животные?|Sì, mi piacciono molto.|Sì, mi piace la pizza.|No, sono alto.', 'Anche a me!|И мне тоже!|Che bello!|Che brutto, grazie.|Prego.']),
  DI('id12', 1, 542, '🚆', 'На вокзале', 'Controllore', '🧑‍✈️', ['Dove vai?|Куда ты едешь?|Vado a Roma.|Vado il pane.|Mi chiamo Roma.', 'Come vai?|Как ты едешь?|In treno.|In pane.|In mamma.', 'Hai il biglietto?|У тебя есть билет?|Sì, eccolo!|Sì, è giallo?|No, sono piccolo.', 'Buon viaggio!|Счастливого пути!|Grazie, ciao!|Prego, buonanotte.|Scusa, sono stanco.']),
  DI('id13', 1, 547, '🌅', 'Мой день', 'Amica', '👧', ['Che cosa fai la mattina?|Что ты делаешь утром?|Faccio colazione.|Faccio la luna.|Faccio sera.', 'Che cosa mangi a pranzo?|Что ты ешь на обед?|Mangio la pasta.|Mangio la scuola.|Mangio il cielo.', 'E la sera?|А вечером?|Guardo un film.|Guardo la mattina.|Ho cento anni.', 'Buonanotte!|Спокойной ночи!|Buonanotte!|Buongiorno!|Buon pranzo!']),
  DI('id14', 1, 553, '🍦', 'Мороженое', 'Gelataio', '🧑‍🍳', ['Ti piace il gelato?|Тебе нравится мороженое?|Sì, mi piace tanto.|Sì, sono io.|No, ho sei anni.', 'Quale gusto?|Какой вкус?|Cioccolato, per favore.|Cioccolato, buongiorno.|Sono le sette.', 'Anche a me piace il cioccolato!|Мне тоже нравится шоколад!|Che bello!|Che sera!|Mi chiamo gatto.', 'Andiamo al bar?|Пойдём в бар?|Sì, andiamo!|No, sono sei.|Ciao, mamma.']),
  DI('id15', 1, 556, '🤝', 'Новый друг', 'Nuovo amico', '🧒', ['Dove abiti?|Где ты живёшь?|Abito a Roma.|Ho Roma.|Sono Roma.', 'Quanti anni hai?|Сколько тебе лет?|Ho dieci anni.|Sono dieci.|Ho dieci.', 'Hai fratelli?|У тебя есть братья?|Sì, ho un fratello.|Sì, ho un tavolo.|Sì, sono io.', 'Che bello! Siamo amici?|Здорово! Мы друзья?|Sì, siamo amici!|No, siamo case.|Prego!']),
  DI('id16', 2, 605, '🍽️', 'В ресторане', 'Cameriere', '🤵', ['Buonasera! Un tavolo per due?|Добрый вечер! Столик на двоих?|Sì, grazie.|Sì, sono due.|No, buongiorno.', 'Ecco il menù.|Вот меню.|Grazie!|Prego!|Scusa!', 'Cosa desiderate?|Что желаете?|Gli spaghetti, per favore.|Gli spaghetti sono io.|Il tavolo è rosso.', 'Ecco il conto.|Вот счёт.|Grazie, arrivederci!|Grazie, buonanotte!|Scusa, ciao.']),
  DI('id17', 2, 606, '🛍️', 'В магазине', 'Commessa', '👩‍💼', ['Buongiorno! Posso aiutarti?|Добрый день! Могу помочь?|Quanto costa la borsa?|Quanti anni hai?|Che ore sono?', 'Costa venti euro.|Стоит двадцать евро.|Va bene, la prendo.|Va bene, sono io.|Ho venti anni.', 'Vuoi un sacchetto?|Хочешь пакет?|Sì, grazie.|Sì, è rosso.|No, sono otto.', 'Ecco il resto.|Вот сдача.|Grazie, arrivederci!|Grazie, buonanotte!|Scusa, prego.']),
  DI('id18', 2, 607, '🏨', 'В гостинице', 'Receptionist', '🧑‍💼', ['Buonasera! Ha una prenotazione?|Добрый вечер! У вас есть бронь?|Sì, mi chiamo Rossi.|Sì, sono le due.|No, ho fame.', 'Ecco la chiave.|Вот ключ.|Grazie mille!|Prego!|Scusa!', 'La camera è al terzo piano.|Комната на третьем этаже.|Va bene, grazie.|Va bene, sono io.|Mi chiamo Luca.', 'Buonanotte!|Спокойной ночи!|Buonanotte!|Buongiorno!|Arrivederci, scusa.']),
  DI('id19', 2, 608, '🎭', 'Карнавал', 'Amico in maschera', '🎭', ['Che bella maschera!|Какая красивая маска!|Grazie, sono un pirata.|Grazie, ho sei anni.|Prego, buonanotte.', 'Giochiamo con i coriandoli?|Поиграем с конфетти?|Sì, che bello!|No, grazie, è pane.|Sì, sono lunedì.', 'Hai fame?|Ты голоден?|Sì, vorrei un dolce.|Sì, sono una maschera.|No, ho otto anni.', 'Buon Carnevale!|С Карнавалом!|Buon Carnevale!|Buonanotte!|Arrivederci, Natale.']),
  DI('id20', 2, 617, '🕒', 'Который час?', 'Passante', '🧑', ['Scusa, che ore sono?|Извини, который час?|Sono le tre.|Sono tre anni.|Sono Anna.', 'Siamo in ritardo?|Мы опаздываем?|No, il film inizia alle quattro.|No, il film è blu.|Sì, sono io.', 'Allora andiamo!|Тогда идём!|Sì, andiamo!|Sì, sono le tre.|No, ho fame.', 'A dopo!|Увидимся!|A dopo!|Buonanotte!|Quanti anni hai?'])
];

const IT_SONGS = [
  SO('is1', 0, 506, '🔢', 'Считалка', ['Uno, due, tre, ecco il re!|Раз, два, три, вот король!|re|pane|luna', 'Quattro, cinque, sei, io e voi!|Четыре, пять, шесть, я и вы!|voi|gatto|sole', 'Sette, otto, nove, piove, piove!|Семь, восемь, девять, дождь идёт!|piove|casa|mela', 'Dieci! Ora contiamo ancora!|Десять! Теперь считаем ещё раз!|ancora|pizza|palla']),
  SO('is2', 0, 508, '🌈', 'Цвета', ['Rosso, rosso, il mio cuore!|Красный, красный — моё сердце!|cuore|gatto|pane', 'Giallo, giallo, come il sole!|Жёлтый, как солнце!|sole|cane|mare', 'Blu, blu, il mare e il cielo!|Синий — море и небо!|cielo|cane|pane', 'Verde, verde, un bel prato!|Зелёный — красивый луг!|prato|scarpa|luna']),
  SO('is3', 0, 509, '👨‍👩‍👧', 'Семья', ['Mamma, mamma, ti voglio bene!|Мама, мама, я тебя люблю!|bene|pane|mare', 'Papà, papà, vieni qui!|Папа, папа, иди сюда!|qui|su|giù', 'Nonna, nonna, una torta!|Бабушка, бабушка, торт!|torta|porta|scarpa', 'Nonno, nonno, una storia!|Дедушка, дедушка, сказка!|storia|palla|rana']),
  SO('is4', 0, 511, '🐾', 'Голоса животных', ['Il gatto fa miao, miao!|Кот мяукает!|miao|bau|muu', 'Il cane fa bau, bau!|Собака лает!|bau|miao|cip', 'La mucca fa muu, muu!|Корова мычит!|muu|bau|miao', 'L’uccello fa cip, cip!|Птичка чирикает!|cip|bau|muu']),
  SO('is5', 0, 512, '🧍', 'Моё тело', ['Ho due occhi per guardare,|У меня два глаза, чтобы смотреть,|guardare|mangiare|dormire', 'due orecchie per ascoltare,|два уха, чтобы слушать,|ascoltare|cantare|ballare', 'una bocca per cantare,|рот, чтобы петь,|cantare|parlare|ballare', 'e due piedi per ballare!|и две ноги, чтобы танцевать!|ballare|dormire|mangiare']),
  SO('is6', 0, 513, '🍕', 'Вкусная песенка', ['Pane e latte, che bontà!|Хлеб и молоко, как вкусно!|bontà|città|pizza', 'Pizza calda, pizza buona!|Горячая пицца, вкусная пицца!|buona|luna|rosa', 'Banana e mela, che bontà!|Банан и яблоко, как вкусно!|mela|gatto|pane', 'Succo fresco, che bontà!|Свежий сок, как вкусно!|fresco|caldo|blu']),
  SO('is7', 0, 517, '📅', 'Дни недели', ['Lunedì, martedì, mercoledì,|Понедельник, вторник, среда,|mercoledì|giovedì|sabato', 'giovedì, venerdì, sabato e poi…|четверг, пятница, суббота, и потом…|poi|noi|voi', 'La domenica si riposa!|В воскресенье отдыхают!|riposa|rosa|cosa', 'Che bella settimana!|Какая красивая неделя!|settimana|mattina|campana']),
  SO('is8', 0, 518, '⛅', 'Погода', ['Il sole splende, che bel giorno!|Солнце светит, какой чудесный день!|giorno|forno|torno', 'La pioggia cade, plin, plin, plin!|Дождь капает, плин-плин-плин!|plin|din|don', 'Il vento soffia, fa freddo!|Ветер дует, холодно!|freddo|caldo|pioggia', 'La neve è bianca e soffice!|Снег белый и мягкий!|soffice|pesante|rossa']),
  SO('is9', 0, 519, '🏃', 'Двигайся!', ['Corro, corro, corro forte!|Бегу, бегу, бегу быстро!|forte|piano|lento', 'Salto, salto, salto in alto!|Прыгаю, прыгаю высоко!|alto|basso|piccolo', 'Nuoto, nuoto nel mare blu!|Плаваю, плаваю в синем море!|blu|rosso|verde', 'Ballo, ballo, che bella festa!|Танцую, танцую, какой чудесный праздник!|festa|testa|finestra']),
  SO('is10', 0, 520, '🌙', 'Колыбельная', ['Buonanotte, buonanotte, la luna è qui!|Спокойной ночи, луна здесь!|qui|lì|su', 'Le stelle brillano nel blu!|Звёзды сияют в синеве!|blu|su|più', 'Chiudi gli occhi, fai la nanna!|Закрой глаза, спи!|nanna|mamma|canna', 'Sogni d’oro, dolce nanna!|Золотых снов, сладкий сон!|nanna|mamma|canna']),
  SO('is11', 1, 532, '🏙️', 'Мой город', ['In città c’è un grande parco,|В городе есть большой парк,|parco|barco|banco', 'e una piazza con la fontana,|и площадь с фонтаном,|fontana|montagna|lana', 'Il bar vende il gelato,|В баре продают мороженое,|gelato|mercato|prato', 'e la scuola è sempre qui!|а школа всегда здесь!|qui|lì|su']),
  SO('is12', 1, 534, '🌤️', 'Времена года', ['Primavera, fiori e sole,|Весна, цветы и солнце,|sole|mare|luna', 'Estate, mare e gelato,|Лето, море и мороженое,|gelato|prato|mercato', 'Autunno, foglie gialle,|Осень, жёлтые листья,|gialle|rosse|belle', 'Inverno, neve e freddo!|Зима, снег и холод!|freddo|caldo|vento'])
];
