// Сказки и басни в формате чтения (простые пересказы классических сюжетов).
// 2 класс — совсем простые, 3 класс — в настоящем времени, 4 класс — в Past Simple (как в модуле «Tell the story!»).
// order — номера строк текста (с нуля) в правильном порядке для игры «расставь события».
const TALES = [
  // ===== Мир 1 =====
  { id: 90, title: 'Репка', icon: '🥕', type: 'read', story: 'Старая русская сказка на английском. Кто поможет вытащить репку?', nextLabel: 'Вопросы по сказке ➜',
    text: [{ en: 'Grandpa has a big turnip.', ru: 'У дедушки большая репка.' }, { en: "Grandpa pulls. He can't pull it.", ru: 'Дедушка тянет. Он не может её вытащить.' },
      { en: 'Grandma helps.', ru: 'Бабушка помогает.' }, { en: 'The girl helps.', ru: 'Внучка помогает.' }, { en: 'The dog helps.', ru: 'Собака помогает.' },
      { en: 'The cat helps.', ru: 'Кошка помогает.' }, { en: 'The mouse helps.', ru: 'Мышка помогает.' }, { en: 'Pull, pull, pull! The turnip is out!', ru: 'Тяни-потяни! Репка вытащена!' }],
    qs: [{ en: 'Who has a big turnip?', ru: 'У кого большая репка?', ans: 'Grandpa', opts: ['Grandpa', 'The dog', 'The cat'] },
      { en: 'Who helps first?', ru: 'Кто помогает первой?', ans: 'Grandma', opts: ['Grandma', 'The dog', 'The mouse'] },
      { en: 'Who helps last?', ru: 'Кто помогает последней?', ans: 'The mouse', opts: ['The mouse', 'The cat', 'The girl'] },
      { en: 'Is the turnip out at the end?', ru: 'Репка вытащена в конце?', ans: 'Yes, it is.', opts: ['Yes, it is.', "No, it isn't.", "No, it can't."] }],
    order: [0, 2, 6, 7],
    sents: [{ en: 'Grandpa has a big turnip.', ru: 'У дедушки большая репка.' }, { en: 'The dog helps.', ru: 'Собака помогает.' }, { en: 'The turnip is out!', ru: 'Репка вытащена!' }] },
  { id: 91, title: 'Курочка и пшеница', icon: '🐔', type: 'read', story: 'Маленькая курочка просит помочь, но никто не хочет работать.', nextLabel: 'Вопросы по сказке ➜',
    text: [{ en: 'A little hen has some wheat.', ru: 'У маленькой курочки есть пшеница.' }, { en: 'She asks the dog to help.', ru: 'Она просит собаку помочь.' },
      { en: 'The dog says no.', ru: 'Собака говорит нет.' }, { en: 'She asks the cat to help.', ru: 'Она просит кошку помочь.' }, { en: 'The cat says no.', ru: 'Кошка говорит нет.' },
      { en: 'The hen works and makes a cake.', ru: 'Курочка работает и печёт пирог.' }, { en: 'Now the dog and the cat want some cake.', ru: 'Теперь собака и кошка хотят пирога.' },
      { en: 'The hen says no. She eats the cake with her chicks.', ru: 'Курочка говорит нет. Она ест пирог со своими цыплятами.' }],
    qs: [{ en: 'What does the hen have?', ru: 'Что есть у курочки?', ans: 'Some wheat', opts: ['Some wheat', 'Some milk', 'A big turnip'] },
      { en: 'Who says no?', ru: 'Кто говорит нет?', ans: 'The dog and the cat', opts: ['The dog and the cat', 'The mouse and the pig', 'Nobody'] },
      { en: 'What does the hen make?', ru: 'Что печёт курочка?', ans: 'A cake', opts: ['A cake', 'A pizza', 'A sandwich'] },
      { en: 'Who eats the cake?', ru: 'Кто ест пирог?', ans: 'The hen and her chicks', opts: ['The hen and her chicks', 'The dog', 'The cat'] }],
    order: [0, 1, 5, 7],
    sents: [{ en: 'The dog says no.', ru: 'Собака говорит нет.' }, { en: 'The hen makes a cake.', ru: 'Курочка печёт пирог.' }, { en: 'She asks the cat to help.', ru: 'Она просит кошку помочь.' }] },

  // ===== Мир 2 =====
  { id: 92, title: 'Лев и мышка', icon: '🦁', type: 'read', story: 'Знаменитая басня. Кто сильнее: большой лев или маленькая мышка?', nextLabel: 'Вопросы по басне ➜',
    text: [{ en: 'A big lion sleeps in the forest.', ru: 'Большой лев спит в лесу.' }, { en: 'A little mouse runs over the lion.', ru: 'Маленькая мышка пробегает по льву.' },
      { en: 'The lion wakes up. He is angry.', ru: 'Лев просыпается. Он злится.' }, { en: 'He catches the mouse.', ru: 'Он ловит мышку.' },
      { en: 'The mouse says, "Please, let me go!"', ru: 'Мышка говорит: «Пожалуйста, отпусти меня!»' }, { en: 'The lion smiles and lets the mouse go.', ru: 'Лев улыбается и отпускает мышку.' },
      { en: 'Next day some hunters catch the lion in a net.', ru: 'На следующий день охотники ловят льва в сеть.' }, { en: 'The little mouse comes and cuts the net.', ru: 'Маленькая мышка приходит и грызёт сеть.' },
      { en: 'Now the lion is free. They are friends.', ru: 'Теперь лев свободен. Они друзья.' }],
    qs: [{ en: 'Where does the lion sleep?', ru: 'Где спит лев?', ans: 'In the forest', opts: ['In the forest', 'In the zoo', 'In the house'] },
      { en: 'Why is the lion angry?', ru: 'Почему лев злится?', ans: 'The mouse runs over him', opts: ['The mouse runs over him', 'He is hungry', 'He is sad'] },
      { en: 'Who helps the lion?', ru: 'Кто помогает льву?', ans: 'The mouse', opts: ['The mouse', 'The hunter', 'The tiger'] },
      { en: 'How are they at the end?', ru: 'Кем они становятся в конце?', ans: 'Friends', opts: ['Friends', 'Angry', 'Sad'] }],
    order: [0, 3, 6, 8],
    sents: [{ en: 'A big lion sleeps.', ru: 'Большой лев спит.' }, { en: 'The mouse helps the lion.', ru: 'Мышка помогает льву.' }, { en: 'They are friends.', ru: 'Они друзья.' }] },
  { id: 93, title: 'Городская и деревенская мышки', icon: '🐭', type: 'read', story: 'Две мышки-подружки живут по-разному. Где лучше?', nextLabel: 'Вопросы по сказке ➜',
    text: [{ en: 'A town mouse visits a country mouse.', ru: 'Городская мышка приходит в гости к деревенской.' }, { en: 'The country mouse has bread and cheese.', ru: 'У деревенской мышки есть хлеб и сыр.' },
      { en: 'The town mouse says, "This is boring!"', ru: 'Городская мышка говорит: «Как скучно!»' }, { en: '"Come to my house in the town!"', ru: '«Пойдём ко мне в город!»' },
      { en: 'The town house is big and the food is great.', ru: 'Городской дом большой, а еда отличная.' }, { en: 'But a cat comes! The mice run away.', ru: 'Но приходит кошка! Мышки убегают.' },
      { en: 'The country mouse is scared.', ru: 'Деревенская мышка напугана.' }, { en: '"I like my quiet home," says the country mouse.', ru: '«Мне нравится мой тихий дом», — говорит деревенская мышка.' },
      { en: 'She goes home and is happy.', ru: 'Она идёт домой и счастлива.' }],
    qs: [{ en: 'Who visits the country mouse?', ru: 'Кто приходит к деревенской мышке?', ans: 'The town mouse', opts: ['The town mouse', 'The cat', 'The dog'] },
      { en: 'What does the country mouse have?', ru: 'Что есть у деревенской мышки?', ans: 'Bread and cheese', opts: ['Bread and cheese', 'Pizza and cake', 'Rice and soup'] },
      { en: 'Who comes to the town house?', ru: 'Кто приходит в городской дом?', ans: 'A cat', opts: ['A cat', 'A dog', 'A bird'] },
      { en: 'Where is the country mouse happy?', ru: 'Где деревенская мышка счастлива?', ans: 'At home in the country', opts: ['At home in the country', 'In the town', 'In the big house'] }],
    order: [0, 3, 5, 8],
    sents: [{ en: 'The country mouse has bread.', ru: 'У деревенской мышки есть хлеб.' }, { en: 'A cat comes.', ru: 'Приходит кошка.' }, { en: 'She is happy at home.', ru: 'Она счастлива дома.' }] },
  { id: 94, title: 'Лиса и виноград', icon: '🍇', type: 'read', story: 'Хитрая лиса очень хочет достать виноград. Получится ли?', nextLabel: 'Вопросы по басне ➜',
    text: [{ en: 'A fox is hungry.', ru: 'Лиса голодна.' }, { en: 'She sees some nice grapes on a tree.', ru: 'Она видит на дереве красивый виноград.' },
      { en: 'The grapes are high.', ru: 'Виноград высоко.' }, { en: "She jumps and jumps, but she can't get them.", ru: 'Она прыгает и прыгает, но не может их достать.' },
      { en: 'She is tired.', ru: 'Она устала.' }, { en: '"These grapes are sour," says the fox.', ru: '«Этот виноград кислый», — говорит лиса.' }, { en: 'She goes away.', ru: 'Она уходит.' }],
    qs: [{ en: 'What does the fox see?', ru: 'Что видит лиса?', ans: 'Some grapes', opts: ['Some grapes', 'An apple', 'A cake'] },
      { en: 'Can the fox get the grapes?', ru: 'Может ли лиса достать виноград?', ans: "No, she can't.", opts: ["No, she can't.", 'Yes, she can.', 'Yes, she does.'] },
      { en: 'How does the fox feel at first?', ru: 'Что чувствует лиса в начале?', ans: 'Hungry', opts: ['Hungry', 'Sleepy', 'Scared'] },
      { en: 'What does she say about the grapes?', ru: 'Что она говорит о винограде?', ans: 'They are sour', opts: ['They are sour', 'They are sweet', 'They are red'] }],
    order: [0, 1, 3, 5],
    sents: [{ en: 'A fox is hungry.', ru: 'Лиса голодна.' }, { en: 'The grapes are high.', ru: 'Виноград высоко.' }, { en: "She can't get the grapes.", ru: 'Она не может достать виноград.' }] },

  // ===== Мир 3 (Past Simple) =====
  { id: 95, title: 'Черепаха и заяц', icon: '🐢', type: 'read', story: 'Кто победит в гонке: быстрый заяц или медленная черепаха?', nextLabel: 'Вопросы по басне ➜',
    text: [{ en: 'A hare met a tortoise.', ru: 'Заяц встретил черепаху.' }, { en: 'The hare laughed, "You are slow!"', ru: 'Заяц засмеялся: «Ты медленная!»' },
      { en: 'The tortoise said, "Let\'s have a race."', ru: 'Черепаха сказала: «Давай устроим гонку».' }, { en: 'The hare ran fast and was far ahead.', ru: 'Заяц быстро бежал и был далеко впереди.' },
      { en: 'He was tired and slept under a tree.', ru: 'Он устал и уснул под деревом.' }, { en: 'The tortoise walked and walked.', ru: 'Черепаха шла и шла.' },
      { en: 'She did not stop.', ru: 'Она не останавливалась.' }, { en: 'The tortoise won the race!', ru: 'Черепаха выиграла гонку!' }, { en: 'Slow and steady wins.', ru: 'Тише едешь — дальше будешь.' }],
    qs: [{ en: 'Who laughed at the tortoise?', ru: 'Кто смеялся над черепахой?', ans: 'The hare', opts: ['The hare', 'The fox', 'The lion'] },
      { en: 'What did the hare do in the race?', ru: 'Что сделал заяц в гонке?', ans: 'He slept under a tree', opts: ['He slept under a tree', 'He ran all the way', 'He ate lunch'] },
      { en: 'Did the tortoise stop?', ru: 'Остановилась ли черепаха?', ans: "No, she didn't.", opts: ["No, she didn't.", 'Yes, she did.', 'Yes, she was.'] },
      { en: 'Who won the race?', ru: 'Кто выиграл гонку?', ans: 'The tortoise', opts: ['The tortoise', 'The hare', 'Nobody'] }],
    order: [0, 3, 4, 7],
    sents: [{ en: 'The hare ran fast.', ru: 'Заяц быстро бежал.' }, { en: 'The tortoise did not stop.', ru: 'Черепаха не останавливалась.' }, { en: 'The tortoise won the race.', ru: 'Черепаха выиграла гонку.' }] },
  { id: 96, title: 'Муравей и стрекоза', icon: '🐜', type: 'read', story: 'Лето пролетело, наступила зима. Кто подготовился лучше?', nextLabel: 'Вопросы по басне ➜',
    text: [{ en: 'In summer, a grasshopper sang and played all day.', ru: 'Летом кузнечик пел и играл весь день.' }, { en: 'An ant worked hard. He carried food home.', ru: 'Муравей усердно работал. Он носил еду домой.' },
      { en: '"Come and play!" said the grasshopper.', ru: '«Иди играть!» — сказал кузнечик.' }, { en: '"No," said the ant. "I must get food for winter."', ru: '«Нет, — сказал муравей. — Мне нужно запасти еду на зиму».' },
      { en: 'Winter came. It was cold and snowy.', ru: 'Пришла зима. Было холодно и снежно.' }, { en: 'The grasshopper was hungry. He had no food.', ru: 'Кузнечик был голоден. У него не было еды.' },
      { en: 'He went to the ant\'s house.', ru: 'Он пошёл к дому муравья.' }, { en: 'The ant gave him some food. "Next summer, work too!" he said.', ru: 'Муравей дал ему еды. «В следующее лето тоже работай!» — сказал он.' }],
    qs: [{ en: 'What did the grasshopper do in summer?', ru: 'Что делал кузнечик летом?', ans: 'Sang and played', opts: ['Sang and played', 'Worked hard', 'Slept'] },
      { en: 'What did the ant do?', ru: 'Что делал муравей?', ans: 'Worked hard', opts: ['Worked hard', 'Played', 'Sang'] },
      { en: 'What was the weather in winter?', ru: 'Какая была погода зимой?', ans: 'Cold and snowy', opts: ['Cold and snowy', 'Hot and sunny', 'Warm and rainy'] },
      { en: 'Who gave food?', ru: 'Кто дал еду?', ans: 'The ant', opts: ['The ant', 'The hare', 'The mouse'] }],
    order: [0, 1, 4, 7],
    sents: [{ en: 'The ant worked hard.', ru: 'Муравей усердно работал.' }, { en: 'Winter came.', ru: 'Пришла зима.' }, { en: 'The grasshopper was hungry.', ru: 'Кузнечик был голоден.' }] },
  { id: 97, title: 'Мальчик и волк', icon: '🐺', type: 'read', story: 'Что случается, когда часто обманываешь? Прочитай басню.', nextLabel: 'Вопросы по басне ➜',
    text: [{ en: 'A boy looked after sheep on a hill.', ru: 'Мальчик пас овец на холме.' }, { en: 'He was bored.', ru: 'Ему было скучно.' },
      { en: '"Wolf! Wolf!" he shouted. "Help me!"', ru: '«Волк! Волк! — закричал он. — Помогите!»' }, { en: 'The people ran to help, but there was no wolf.', ru: 'Люди прибежали на помощь, но волка не было.' },
      { en: 'The boy laughed.', ru: 'Мальчик засмеялся.' }, { en: 'He did it again. The people ran again, and again there was no wolf.', ru: 'Он сделал так снова. Люди снова прибежали, и снова не было волка.' },
      { en: 'One day a real wolf came.', ru: 'Однажды пришёл настоящий волк.' }, { en: 'The boy shouted, "Wolf! Wolf!" but nobody came.', ru: 'Мальчик закричал: «Волк! Волк!», но никто не пришёл.' },
      { en: 'People did not believe him.', ru: 'Люди ему не поверили.' }],
    qs: [{ en: 'What did the boy look after?', ru: 'За кем присматривал мальчик?', ans: 'Sheep', opts: ['Sheep', 'Cows', 'Horses'] },
      { en: 'Why did he shout?', ru: 'Почему он кричал?', ans: 'He was bored', opts: ['He was bored', 'He was happy', 'He was hungry'] },
      { en: 'Was there a wolf at first?', ru: 'Был ли сначала волк?', ans: "No, there wasn't.", opts: ["No, there wasn't.", 'Yes, there was.', "We don't know."] },
      { en: "Why didn't people come at the end?", ru: 'Почему люди не пришли в конце?', ans: "They didn't believe him", opts: ["They didn't believe him", 'They were asleep', 'They were angry'] }],
    order: [0, 2, 6, 8],
    sents: [{ en: 'A boy looked after sheep.', ru: 'Мальчик пас овец.' }, { en: 'He was bored.', ru: 'Ему было скучно.' }, { en: 'A real wolf came.', ru: 'Пришёл настоящий волк.' }] },
  { id: 98, title: 'Три поросёнка', icon: '🐷', type: 'read', story: 'Три поросёнка построили три дома. Чей дом самый крепкий?', nextLabel: 'Вопросы по сказке ➜',
    text: [{ en: 'Three little pigs left home.', ru: 'Три поросёнка ушли из дома.' }, { en: 'The first pig built a house of straw.', ru: 'Первый поросёнок построил дом из соломы.' },
      { en: 'The second pig built a house of sticks.', ru: 'Второй поросёнок построил дом из прутьев.' }, { en: 'The third pig built a house of bricks.', ru: 'Третий поросёнок построил дом из кирпичей.' },
      { en: 'A big bad wolf came. "Little pig, let me in!"', ru: 'Пришёл большой злой волк. «Поросёнок, впусти меня!»' }, { en: 'He blew the straw house down. He blew the stick house down.', ru: 'Он сдул соломенный дом. Он сдул дом из прутьев.' },
      { en: 'The two pigs ran to the brick house.', ru: 'Два поросёнка побежали в кирпичный дом.' }, { en: 'The wolf blew and blew, but the brick house was strong.', ru: 'Волк дул и дул, но кирпичный дом был крепким.' },
      { en: 'The pigs were safe and happy.', ru: 'Поросята были в безопасности и счастливы.' }],
    qs: [{ en: 'What was the first house made of?', ru: 'Из чего был первый дом?', ans: 'Straw', opts: ['Straw', 'Sticks', 'Bricks'] },
      { en: 'Which house was strong?', ru: 'Какой дом был крепким?', ans: 'The brick house', opts: ['The brick house', 'The straw house', 'The stick house'] },
      { en: 'Who came to the houses?', ru: 'Кто пришёл к домам?', ans: 'A big bad wolf', opts: ['A big bad wolf', 'A big bad fox', 'A lion'] },
      { en: 'How did the pigs feel at the end?', ru: 'Что чувствовали поросята в конце?', ans: 'Safe and happy', opts: ['Safe and happy', 'Sad', 'Angry'] }],
    order: [0, 1, 4, 8],
    sents: [{ en: 'The third pig built a house.', ru: 'Третий поросёнок построил дом.' }, { en: 'The wolf blew and blew.', ru: 'Волк дул и дул.' }, { en: 'The pigs were happy.', ru: 'Поросята были счастливы.' }] }
];

// вставляем сказки в миры (в конец мира 1 и 2, а сказки 4 класса — рядом с Past Simple)
TALES.forEach(l => { POOL[l.id] = l; });
ORDER[0].push(90, 91);
ORDER[1].push(92, 93, 94);
ORDER[2].splice(ORDER[2].indexOf(48) + 1, 0, 95, 96);
ORDER[2].splice(ORDER[2].indexOf(49) + 1, 0, 97, 98);
WORLDS.forEach((wd, i) => { wd.lessons = ORDER[i].map(id => POOL[id]); });
